=== stevencapelli/SCA-PatternBOX/editor-plugin/template.java/templates.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- 
  
  Copyright (C) 2003-2012 by Dirk Ehms, www.patternbox.com. 
  All rights reserved. 
  
  This DTD module is identified by the SYSTEM identifier:
  SYSTEM "templates.dtd"

  Version: 1.0
  Date:    2003-09-02

-->

<!ELEMENT templates (role*)>
<!ATTLIST templates
  id        NMTOKEN   #REQUIRED
  version   NMTOKEN   #REQUIRED
>

<!ELEMENT role (import*,annotation?,superclass?,interface*,field*,constructor*,method*)>
<!ATTLIST role
  name      ID                 #REQUIRED
  type      (class|interface|enum)  #REQUIRED
  modifiers CDATA              #IMPLIED
>

<!ELEMENT import EMPTY>
<!ATTLIST import
  type      CDATA   #REQUIRED
>

<!ELEMENT superclass EMPTY>
<!ATTLIST superclass
  type      CDATA   #REQUIRED
>

<!ELEMENT interface EMPTY>
<!ATTLIST interface
  type      CDATA   #REQUIRED
>

<!ELEMENT field (comment?, annotation?)>
<!ATTLIST field
  modifiers CDATA   #IMPLIED
  type      CDATA   #REQUIRED
  name      CDATA   #REQUIRED
  initial   CDATA   #IMPLIED
>

<!ELEMENT constructor (comment?,annotation?,param*,exception*,code?)>
<!ATTLIST constructor
  modifiers CDATA #IMPLIED
>

<!ELEMENT method (comment?,annotation?,param*,exception*,code?)>
<!ATTLIST method
  modifiers CDATA   #IMPLIED
  return    CDATA   #REQUIRED
  name      CDATA   #REQUIRED
  foreach   CDATA   #IMPLIED
>

<!ELEMENT param (comment?)>
<!ATTLIST param
  type      CDATA   #REQUIRED
  name      CDATA   #REQUIRED
>

<!ELEMENT exception EMPTY>
<!ATTLIST exception
  type      CDATA   #REQUIRED
>

<!ELEMENT comment (#PCDATA)>

<!ELEMENT annotation (#PCDATA)>

<!ELEMENT code (#PCDATA|replace)*>

<!ELEMENT replace (#PCDATA)>
<!ATTLIST replace
  initial     CDATA   #REQUIRED
  dependence  IDREF   #REQUIRED
>

=== stevencapelli/SCA-PatternBOX/editor-plugin/template.java/facade.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE templates SYSTEM "templates.dtd">

<!-- Copyright (C) 2003-2012 by Dirk Ehms, www.patternbox.com. All rights reserved. -->

<templates id="facade" version="1.0">

  <!-- ====================================================================== -->
  <role name="Facade" type="class" modifiers="public">

    <field modifiers="private" type="$Subsystem$" name="fSubsystem">
      <comment>stores the subsystem interface</comment>
    </field>

    <constructor modifiers="public">
      <comment>Default constuctor</comment>
      <code>super();</code>
    </constructor>

    <method modifiers="public" return="void" name="regSubsystem">
      <comment>
        This method registers the associated subsystem interface.
      </comment>
      <param type="$Subsystem$" name="subsystem" />
      <code>
        this.fSubsystem = subsystem;
      </code>
    </method>

    <method modifiers="public" return="void" name="callOperation1">
      <comment>
        This method calls a specific operation defined in your model.
      </comment>
      <code>
        fSubsystem.operation1();
      </code>
    </method>

    <method modifiers="public" return="void" name="callOperation2">
      <comment>
        This method calls a specific operation defined in your model.
      </comment>
      <code>
        fSubsystem.operation2();
      </code>
    </method>

    <method modifiers="public" return="void" name="callOperation3">
      <comment>
        This method calls a specific operation defined in your model.
      </comment>
      <code>
        fSubsystem.operation3();
      </code>
    </method>

  </role>

  <!-- ====================================================================== -->
  <role name="Subsystem" type="class" modifiers="public">

    <constructor modifiers="public">
      <code>super();</code>
    </constructor>

    <method modifiers="public" return="void" name="operation1">
      <comment>
        This can be any method of your model.
      </comment>
      <code>
        // TODO: Customize this method based on your application needs.
      </code>
    </method>

    <method modifiers="public" return="void" name="operation2">
      <comment>
        This can be any method of your model.
      </comment>
      <code>
        // TODO: Customize this method based on your application needs.
      </code>
    </method>

    <method modifiers="public" return="void" name="operation3">
      <comment>
        This can be any method of your model.
      </comment>
      <code>
        // TODO: Customize this method based on your application needs.
      </code>
    </method>

  </role>

</templates>

=== stevencapelli/SCA-PatternBOX/editor-plugin/template.java/callback.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE templates SYSTEM "templates.dtd">

<!-- Copyright (C) 2003-2012 by Dirk Ehms, www.patternbox.com. All rights reserved. -->

<templates id="callback" version="1.1">

  <!-- ====================================================================== -->
  <role name="ForwardInterface" type="interface" modifiers="public">
<import type="org.osoa.sca.annotations.*"/>
 <annotation>@Callback(InterfaceCallback.class)</annotation>  
   
 <method modifiers="public" return="void" name="callbackAsynch">
      <comment>
       This method declaration must be implemented by the Server implementations.
      </comment>
<annotation>@OneWay</annotation> 
<param type="java.lang.Object" name="item"/>
    </method>

  
 </role>

<!-- ====================================================================== -->
  <role name="InterfaceCallback" type="interface" modifiers="public">

    <method modifiers="public" return="void" name="callbackResults">
      <comment>
        This method notify back the results to the client.
      </comment>
<param type="java.lang.Object" name="item"/>
    </method>
  </role>

  <!-- ====================================================================== -->
  <role name="ServerImpl" type="class" modifiers="public">
 <import type="org.osoa.sca.annotations.*"/>
<annotation>@Service(ForwardInterface.class)</annotation> 
    <interface type="$ForwardInterface$"/>

    <field modifiers="protected" type="$InterfaceCallback$" name="fInterfaceCallback">
      <comment>
        identify the callback proxy
      </comment>
 <annotation>@Callback</annotation>  
    </field>

   <constructor modifiers="public">
      <comment>Constructor</comment>
      <code>
        super();
      </code>
    </constructor>

    <method modifiers="public" return="void" name="callbackAsynch">
      
	<param type="java.lang.Object" name="item"/>
      <code>
	Object itemResult=doSomething(item);
        fInterfaceCallback.callbackResults(itemResult);
      </code>
    </method>
<method modifiers="private" return="java.lang.Object" name="doSomething">
      
	<param type="java.lang.Object" name="item"/>
      <code>
	 // TODO Write your algorithm code here ...
	return item;
      </code>
    </method>
   </role>

  
  <!-- ====================================================================== -->
  <role name="ClientCallbackImpl" type="class" modifiers="public">
 <import type="org.osoa.sca.annotations.*"/>
    <interface type="$InterfaceCallback$"/>

    <field modifiers="protected" type="ForwardInterface" name="fCallback">
<annotation>@Reference</annotation> 
    </field>

<constructor modifiers="public">
      <comment>Constructor</comment>
      <code>
        super();
      </code>
    </constructor>

    <method modifiers="public" return="void" name="run">
     
      <code>
	Object item;
        fCallback.callbackAsynch(item);
      </code>
    </method>

    <method modifiers="public" return="void" name="callbackResults">
<param type="java.lang.Object" name="items"/>
	<code>
		doSomething(items);
	</code>
     </method>


    <method modifiers="public" return="void" name="doSomething">
     <param type="java.lang.Object" name="item"/>
	<code>
	 //TODO Write your algorithm code here ...
	</code>
     </method>
  </role>

</templates>

=== stevencapelli/SCA-PatternBOX/editor-plugin/template.java/prototype.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE templates SYSTEM "templates.dtd">

<!-- Copyright (C) 2003-2012 by Dirk Ehms, www.patternbox.com. All rights reserved. -->

<templates id="prototype" version="1.1">

  <!-- ====================================================================== -->
  <role name="Prototype" type="interface" modifiers="public">

    <interface type="java.lang.Cloneable"/>

    <method modifiers="public" return="$Prototype$" name="toClone">
      <comment>
        Creates a new instance by cloning itself.
      </comment>
      <exception type="java.lang.CloneNotSupportedException"/>
    </method>

    <method modifiers="public" return="void" name="doSomething">
      <comment>
        This is just a dummy method that can be called by the client. Replace
        this method by another one which you really need.
      </comment>
    </method>

  </role>

  <!-- ====================================================================== -->
  <role name="ConcretePrototype" type="class" modifiers="public">

    <interface type="$Prototype$"/>

    <method modifiers="public" return="$Prototype$" name="toClone">
      <comment>
        Creates a new instance by cloning itself.
      </comment>
      <exception type="java.lang.CloneNotSupportedException"/>
      <code>
        return ($Prototype$) this.clone();
      </code>
    </method>

    <method modifiers="public" return="void" name="doSomething">
      <comment>
        This is just a dummy method that can be called by the client. Replace
        this method by another one which you really need.
      </comment>
      <code/>
    </method>

  </role>

  <!-- ====================================================================== -->
  <role name="Client" type="class" modifiers="public">

    <field modifiers="private final" type="$Prototype$" name="fPrototype">
      <comment>stores the Prototype instance</comment>
    </field>

    <constructor modifiers="public">
      <comment>Constructor</comment>
      <param type="$Prototype$" name="prototype" />
      <code>fPrototype = prototype;</code>
    </constructor>

    <method modifiers="public" return="void" name="usePrototype">
      <comment>
        This is just an example how to use the Prototype pattern. This operation
        must be customized based on your application needs.
      </comment>
      <code>
        // TODO: Customize this method based on your application needs.
        try {
          // create a new prototype without knowing the real implementation class
          $Prototype$ prototype = fPrototype.toClone();
          // call a Prototype method
          prototype.doSomething();
        } catch (CloneNotSupportedException e) {
          // TODO: Handle exception
          e.printStackTrace();
        }
      </code>
    </method>

    <method modifiers="public static" return="void" name="main">
      <comment>
        Run application from command line.
      </comment>
      <param type="java.lang.String[]" name="args" />
      <code>
        new $Client$(new $ConcretePrototype$()).usePrototype();
      </code>
    </method>

  </role>

</templates>

=== stevencapelli/SCA-PatternBOX/editor-plugin/template.java/state.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE templates SYSTEM "templates.dtd">

<!-- Copyright (C) 2003-2012 by Dirk Ehms, www.patternbox.com. All rights reserved. -->

<templates id="state" version="1.1">

  <!-- ====================================================================== -->
  <role name="Context" type="class" modifiers="public">

    <field modifiers="private" type="$State$" name="fState">
      <comment>stores the associated State instance</comment>
    </field>

    <constructor modifiers="public">
      <comment>Constructor</comment>
      <param type="$State$" name="state" />
      <code>
        super();
        fState = state;
      </code>
    </constructor>

    <method modifiers="public" return="void" name="request">
      <comment>
        The Context object delegates all state-specific requests to its
        associated State instance.
      </comment>
      <code>
        // TODO: Customize this method based on your application needs.
        fState.handle(this);
      </code>
    </method>

    <method modifiers="public" return="void" name="changeState">
      <comment>
        This method changes the state of the Context instance.
      </comment>
      <param type="$State$" name="state" />
      <code>
        fState = state;
      </code>
    </method>

  </role>

  <!-- ====================================================================== -->
  <role name="State" type="class" modifiers="public abstract">

    <method modifiers="protected" return="void" name="changeState">
      <comment>
        This method changes the state of the given Context parameter.
      </comment>
      <param type="$Context$" name="context" />
      <param type="$State$" name="state" />
      <code>
        <replace initial="// " dependence="Context">context.changeState(state)</replace>;
      </code>
    </method>

    <method modifiers="public abstract" return="void" name="handle">
      <comment>
      	This abstract method must be implemented by the ConcreteState.
      </comment>
      <param type="$Context$" name="context" />
    </method>

  </role>

  <!-- ====================================================================== -->
  <role name="ConcreteState" type="class" modifiers="public">

    <superclass type="$State$" />

    <constructor modifiers="public">
      <comment>Default constructor</comment>
      <code>
        super();
      </code>
    </constructor>

    <method modifiers="public" return="void" name="handle">
      <comment>
        This method handles a request from a Context instance.
      </comment>
      <param type="$Context$" name="context" />
      <code>
        super.changeState(context, this);
      </code>
    </method>

  </role>

</templates>

=== stevencapelli/SCA-PatternBOX/editor-plugin/template.java/Layer.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE templates SYSTEM "templates.dtd">

<!-- Copyright (C) 2003-2012 by Dirk Ehms, www.patternbox.com. All rights reserved. -->

<templates id="PatternLayer" version="1.1">

  <!-- ====================================================================== -->
  <role name="ApplicationService" type="interface" modifiers="public">
   
 <method modifiers="public" return="Object" name="GUIcommand">
 
<param type="Object" name="o"/>
</method>
 </role>

<!-- ====================================================================== -->
 <role name="QueryService" type="interface" modifiers="public">
 <method modifiers="public" return="Object" name="executeQuery">
 
<param type="java.lang.Object" name="query"/>
</method>

</role>

<!-- ====================================================================== -->
 <role name="PersistenceService" type="interface" modifiers="public">
 <import type="org.osoa.sca.annotations.*"/>
 <method modifiers="public" return="boolean" name="updateData">
<param type="java.lang.Object" name="update"/>
</method>

</role>

<!-- ====================================================================== -->

 <role name="Data" type="class" modifiers="public">
 <import type="org.osoa.sca.annotations.*"/>
<annotation>@Service(interfaces={QueryService.class, PersistenceService.class})</annotation>   
<interface type="$QueryService$"/>
 <interface type="$PersistenceService$"/>

   <constructor modifiers="public">
      <comment>Constructor</comment>
      <code>
        super();
      </code>
    </constructor>

    <method modifiers="public" return="Object" name="executeQuery">
      
	<param type="Object" name="query"/>
	<comment>insert code to query data</comment>
      <code>
	return "";
      </code>
    </method>
	
	<method modifiers="public" return="boolean" name="updateData">
      
	<param type="Object" name="update"/>
	<comment>insert code to update data</comment>
      <code>
	return true;
      </code>
    </method>
   </role>

  <!-- ====================================================================== -->
  
  <role name="Application" type="class" modifiers="public">
 <import type="org.osoa.sca.annotations.*"/>
<annotation>@Service(ApplicationService.class)</annotation>   
<interface type="$ApplicationService$"/>


<field modifiers="protected" type="$QueryService$" name="queryService">
      <comment>
        identify the dependency on Query service
      </comment>
 <annotation>@Reference</annotation>  
    </field>

    <field modifiers="protected" type="$PersistenceService$" name="persistenceService">
      <comment>
        identify the dependency on Persistence service
      </comment>
 <annotation>@Reference</annotation>  
    </field>

   <constructor modifiers="public">
      <comment>Constructor</comment>
      <code>
        super();
      </code>
    </constructor>

    <method modifiers="public" return="Object" name="GIUcommand">
      
	<param type="Object" name="o"/>
      <code>
	o=doSomething();
       return storeData(o);
      </code>
    </method>

<method modifiers="private" return="Object" name="doSomething">
      
	<param type="Object" name="o"/>
        <comment>doSomething</comment>
      <code>
	return "";
      </code>
    </method>

<method modifiers="private" return="boolean" name="storeData">
      
	<param type="Object" name="o"/>
        <comment>store data</comment>
      <code>
	persistenceService.updateData(o);
        return true;
      </code>
    </method>

<method modifiers="private" return="Object" name="queryData">
      
	<param type="Object" name="o"/>
        <comment>query data</comment>
      <code>
	 return queryService.executeQuery(o);
      </code>
    </method>
   </role>
   
  <!-- ====================================================================== -->
  
  <role name="GUI" type="class" modifiers="public">
 <import type="org.osoa.sca.annotations.*"/>

    <field modifiers="protected" type="$AplicationService$" name="applicationService">
     <annotation>@Reference</annotation>  
 </field>

   <constructor modifiers="public">
      <comment>Constructor</comment>
      <code>
        super();
      </code>
    </constructor>

    <method modifiers="public" return="void" name="sendCommand">
      <code>
	applicationService.GUIcommand(o);
        doSomething();
      </code>
    </method>
	
	<method modifiers="private" return="void" name="doSomething">
      
	<comment>doSomething</comment>
    </method>
   </role>
</templates>

=== stevencapelli/SCA-PatternBOX/editor-plugin/template.java/publishsubscribe.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE templates SYSTEM "templates.dtd">

<!-- Copyright (C) 2003-2012 by Dirk Ehms, www.patternbox.com. All rights reserved. -->

<templates id="publishsubscribe" version="1.1">

  <!-- ====================================================================== -->
  <role name="Data" type="class" modifiers="public">  
   <field modifiers="private" type="java.lang.Object" name="item"></field>
<field modifiers="private" type="$Category$" name="category"></field>
<constructor modifiers="public">
      <comment>Constructor</comment>
<param type="java.lang.Object" name="item"/>
<param type="$Category$" name="category"/>
      <code>
        this.item=item;
	this.category=category;
      </code>
    </constructor>

 <method modifiers="public" return="java.lang.Object" name="getData">
      <comment>
       This method sets the Data
      </comment>
	<code>return item;</code>
 </method>
<method modifiers="public" return="Category" name="getCategory">
      <comment>
       This method sets the Category
      </comment>
	<code>return category;</code>
 </method>
 </role>

<!-- ====================================================================== -->
 <role name="Category" type="enum" modifiers="public">  
   
 </role>

<!-- ====================================================================== -->
  <role name="Publisher" type="interface" modifiers="public">

    <method modifiers="public" return="void" name="run">
	<comment>
        This method sends the Data to the Publish Component
	</comment>	
	<param type="$Data$" name="data"/>
	<param type="DispatcherImpl" name="dispatch"/>
    </method>

    <method modifiers="public" return="void" name="setMessage">
	<param type="$Data$" name="data"/>
    </method>
  </role>

  <!-- ====================================================================== -->
  <role name="DispatchPub" type="interface" modifiers="public">
 <import type="org.osoa.sca.annotations.*"/>

    <method modifiers="public" return="void" name="send">
	<annotation>@OneWay</annotation>      	
	<param type="$Data$" name="data"/>
	<param type="DispatcherImpl" name="dispatch"/>
    </method>

  </role>
  <!-- ====================================================================== -->
 <role name="DispatchSub" type="interface" modifiers="public">
 <import type="org.osoa.sca.annotations.*"/>

    <method modifiers="public" return="void" name="subscribe">
	<annotation>@OneWay</annotation>      	
	<param type="$Category$" name="category"/>
   <param type="int" name="b"/>
<param type="DispatcherImpl" name="dispatch"/>
 </method>
 <method modifiers="public" return="void" name="removeSubscribe">
	<annotation>@OneWay</annotation>      	
	<param type="$Category$" name="category"/>
   <param type="int" name="b"/>
<param type="DispatcherImpl" name="dispatch"/>
 </method>
  </role>
  <!-- ====================================================================== -->
<role name="SubscriberCommunicate" type="interface" modifiers="public">

<method modifiers="public" return="void" name="communicate">
	<annotation>@OneWay</annotation>
	<param type="$Data$" name="data"/>
</method>
<method modifiers="public" return="void" name="subscribe">
	<param type="$Category$" name="category"/>
	<param type="int" name="subscriberNum"/>
	<param type="DispatcherImpl" name="dispatcher"/>
</method>
<method modifiers="public" return="void" name="removeSubscribe">
	<param type="$Category$" name="category"/>
	<param type="int" name="subscriberNum"/>
	<param type="DispatcherImpl" name="dispatcher"/>
</method>
  </role>
  <!-- ====================================================================== -->
 <role name="RowList" type="class" modifiers="public">  
   <field modifiers="private" type="int" name="subscriberNumber"></field>
<field modifiers="private" type="Category" name="category"></field>
<constructor modifiers="public">
      <comment>Constructor</comment>
<param type="$Category$" name="category"/>
<param type="int" name="subNum"/>

      <code>
        this.subscriberNumber = subNum;
	this.category = category;
      </code>
    </constructor>

 <method modifiers="public" return="int" name="getSubscriber">
      <comment>
       This method gets the subscriber's number
      </comment>
	<code>return subscriberNumber;</code>
 </method>
<method modifiers="public" return="Category" name="getCategory">
      <comment>
       This method gets the Category
      </comment>
	<code>return category;</code>
 </method>

<method modifiers="public" return="void" name="setCategory">
      <comment>
       This method sets the Category
      </comment>
<param type="$Category$" name="category"/>
	<code>this.category=category;</code>
 </method>

<method modifiers="public" return="void" name="setSubscriber">
      <comment>
       This method sets the subscriber's number
      </comment>
<param type="int" name="subscriber"/>
	<code>this.subscriberNumber=subscriber;</code>
 </method>
 </role>

<!-- ====================================================================== --> 
 <role name="PublisherImpl" type="class" modifiers="public">
 <import type="org.osoa.sca.annotations.*"/>
<annotation>@Service(Publisher.class)</annotation>     
<interface type="$Publisher$"/>

    <field modifiers="protected" type="DispatchPub" name="dispatch">
	<annotation>@Reference</annotation> 
    </field>
<field modifiers="private" type="Data" name="data">
    </field>
<constructor modifiers="public">
      <comment>Constructor</comment>
      <code>
        super();
      </code>
    </constructor>

    <method modifiers="public" return="void" name="run">
	<param type="$Data$" name="data"/>
	<param type="DispatcherImpl" name="d"/>
      <code>
	dispatch.send(data,d);
      </code>
    </method>

    <method modifiers="public" return="void" name="setMessage">
	<comment>This method sets the Message</comment>     
	<param type="$Data$" name="data"/>
	<code>
	this.data=data;
	</code>
     </method>

  </role>
 <!-- ====================================================================== -->
  <role name="DispatcherImpl" type="class" modifiers="public">
 <import type="org.osoa.sca.annotations.*"/>
<import type="java.util.LinkedList"/>

<annotation>@Service(interfaces={DispatchPub.class, DispatchSub.class})</annotation>     
<interface type="$DispatchPub$"/>
<interface type="$DispatchSub$"/>

    <field modifiers="private" type="SubscriberCommunicate []" name="listSubscriber">
	<annotation>@Reference</annotation> 
    </field>
<field modifiers="private" type="Java.util.LinkedList&lt;RowList&gt;" name="table"> </field>

<constructor modifiers="public">
      <comment>Constructor</comment>
      <code>
        table=new LinkedList&lt;RowList&gt;();
      </code>
    </constructor>

    <method modifiers="public" return="void" name="subscribe">     
	<param type="Category" name="category"/>  
<param type="int" name="b"/>
<param type="DispatcherImpl" name="dispatch"/> 
	<code>
	RowList row=new RowList(category,b);
	dispatch.table.add(row);
      </code>
    </method>

    <method modifiers="public" return="void" name="send">  
	 
	<param type="$Data$" name="data"/>
	<param type="DispatcherImpl" name="dispatch"/>
	<code>
	Category dataCategory=data.getCategory();
		for(RowList row: dispatch.table)
		{
			if(row.getCategory()==dataCategory)
			{
				int i=row.getSubscriber();
			  listSubscriber[i].communicate(data);
			}
		}
	</code>
     </method>
 <method modifiers="public" return="void" name="removeSubscribe">
	<comment>This method removes a Subscriber from the list</comment>
	<param type="Category" name="category"/>
	<param type="int" name="b"/>
<param type="DispatcherImpl" name="dispatch"/>
	<code>
	int cont=0;
		for(RowList row: dispatch.table)
		{
			if((row.getCategory()==category) &amp;&amp; (row.getSubscriber()==b))
			{
				dispatch.table.remove(cont);
				break;
			}
			cont++;
		}
	</code>
     </method>

  </role>
 <!-- ====================================================================== -->

  <role name="SubscriberImpl" type="class" modifiers="public">
 <import type="org.osoa.sca.annotations.*"/>
<annotation>@Service(SubscriberCommunicate.class)</annotation>     
<interface type="$SubscriberCommunicate$"/>

    <field modifiers="protected" type="DispatchSub" name="dispatchSub">
	<annotation>@Reference</annotation> 
    </field>

<constructor modifiers="public">
      <comment>Constructor</comment>
      <code>
        super();
      </code>
    </constructor>

    <method modifiers="public" return="void" name="communicate">
      <param type="$Data$" name="data"/>
	<code>
	doSomething(data);
      </code>
    </method>

<method modifiers="public" return="void" name="doSomething">
      <param type="$Data$" name="data"/>
	<code>
	//TODO Write your algorithm here...
      </code>
    </method>

<method modifiers="public" return="void" name="subscribe">
      <param type="$Category$" name="category"/>
	<param type="int" name="subscriberNum"/>
	<param type="$DispatcherImpl$" name="dispatcher"/>
	<code>
	dispatchSub.subscribe(category, subscriberNum, dispatcher);
      </code>
    </method>

<method modifiers="public" return="void" name="removeSubscribe">
      <param type="$Category$" name="category"/>
	<param type="int" name="subscriberNum"/>
	<param type="$DispatcherImpl$" name="dispatcher"/>
	<code>
	dispatchSub.removeSubscribe(category, subscriberNum, dispatcher);
      </code>
    </method>
  </role>

</templates>
