=== stevencapelli/SCA-PatternBOX/editor-plugin/template.java/templates.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- 
  
  Copyright (C) 2003-2012 by Dirk Ehms, www.patternbox.com. 
  All rights reserved. 
  
  This DTD module is identified by the SYSTEM identifier:
  SYSTEM "templates.dtd"

  Version: 1.0
  Date:    2003-09-02

-->

<!ELEMENT templates (role*)>
<!ATTLIST templates
  id        NMTOKEN   #REQUIRED
  version   NMTOKEN   #REQUIRED
>

<!ELEMENT role (import*,annotation?,superclass?,interface*,field*,constructor*,method*)>
<!ATTLIST role
  name      ID                 #REQUIRED
  type      (class|interface|enum)  #REQUIRED
  modifiers CDATA              #IMPLIED
>

<!ELEMENT import EMPTY>
<!ATTLIST import
  type      CDATA   #REQUIRED
>

<!ELEMENT superclass EMPTY>
<!ATTLIST superclass
  type      CDATA   #REQUIRED
>

<!ELEMENT interface EMPTY>
<!ATTLIST interface
  type      CDATA   #REQUIRED
>

<!ELEMENT field (comment?, annotation?)>
<!ATTLIST field
  modifiers CDATA   #IMPLIED
  type      CDATA   #REQUIRED
  name      CDATA   #REQUIRED
  initial   CDATA   #IMPLIED
>

<!ELEMENT constructor (comment?,annotation?,param*,exception*,code?)>
<!ATTLIST constructor
  modifiers CDATA #IMPLIED
>

<!ELEMENT method (comment?,annotation?,param*,exception*,code?)>
<!ATTLIST method
  modifiers CDATA   #IMPLIED
  return    CDATA   #REQUIRED
  name      CDATA   #REQUIRED
  foreach   CDATA   #IMPLIED
>

<!ELEMENT param (comment?)>
<!ATTLIST param
  type      CDATA   #REQUIRED
  name      CDATA   #REQUIRED
>

<!ELEMENT exception EMPTY>
<!ATTLIST exception
  type      CDATA   #REQUIRED
>

<!ELEMENT comment (#PCDATA)>

<!ELEMENT annotation (#PCDATA)>

<!ELEMENT code (#PCDATA|replace)*>

<!ELEMENT replace (#PCDATA)>
<!ATTLIST replace
  initial     CDATA   #REQUIRED
  dependence  IDREF   #REQUIRED
>

=== stevencapelli/SCA-PatternBOX/editor-plugin/template.java/fifo.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE templates SYSTEM "templates.dtd">

<!-- Copyright (C) 2003-2012 by Dirk Ehms, www.patternbox.com. All rights reserved. -->

<templates id="fifo" version="1.1">

  <!-- ====================================================================== -->
  <role name="Sender" type="interface" modifiers="public">
   
 <method modifiers="public" return="void" name="enqueue">
      <comment>
       This method must be implemented by the Sender component.
      </comment>

<param type="java.lang.Object" name="item"/>
<param type="FifoImpl" name="fifo"/>
    </method>

  
 </role>

<!-- ====================================================================== -->
 <role name="Receiver" type="interface" modifiers="public">
 <method modifiers="public" return="void" name="dequeue">
      <comment>
       This method must be implemented by the Receiver component.
      </comment>
<param type="FifoImpl" name="fifo"/>
    </method>
 </role>

<!-- ====================================================================== -->
  <role name="FifoEnqueue" type="interface" modifiers="public">
<import type="org.osoa.sca.annotations.*"/>
    <method modifiers="public" return="void" name="enqueue">
      <comment>
        This method enqueues an object into the fifo.
      </comment>
<annotation>@OneWay</annotation> 
<param type="java.lang.Object" name="item"/>
<param type="FifoImpl" name="fifo"/>
    </method>
  </role>

  <!-- ====================================================================== -->
  <role name="FifoDequeue" type="interface" modifiers="public">

    <method modifiers="public" return="java.lang.Object" name="dequeue">
      <comment>
        This method dequeues an object from the fifo.
      </comment>
<param type="FifoImpl" name="fifo"/>
    </method>
  </role>

  <!-- ====================================================================== -->
 <role name="SenderImpl" type="class" modifiers="public">
 <import type="org.osoa.sca.annotations.*"/>
<annotation>@Service(Sender.class)</annotation> 
    <interface type="$Sender$"/>

    <field modifiers="protected" type="$FifoEnqueue$" name="fifoenqueue">
      <comment>
        identify the dependency on Fifo service
      </comment>
 <annotation>@Reference</annotation>  
    </field>

   <constructor modifiers="public">
      <comment>Constructor</comment>
      <code>
        super();
      </code>
    </constructor>

    <method modifiers="public" return="void" name="enqueue">
      
	<param type="java.lang.Object" name="item"/>
<param type="FifoImpl" name="fifo"/>
      <code>
	fifoenqueue.enqueue(item, fifo);
      </code>
    </method>
   </role>

  <!-- ====================================================================== -->
  <role name="FifoImpl" type="class" modifiers="public">
 <import type="org.osoa.sca.annotations.*"/>
  <import type="java.util.LinkedList"/>
<annotation>@Service(interfaces={FifoEnqueue.class, FifoDequeue.class})</annotation>   
<interface type="$FifoEnqueue$"/>
 <interface type="$FifoDequeue$"/>
    <field modifiers="private" type="java.util.LinkedList&lt;Object&gt;" name="queue">
    </field>

<constructor modifiers="public">
      <comment>Constructor</comment>
      <code>
       queue=new LinkedList&lt;Object&gt;();
      </code>
    </constructor>

    <method modifiers="public" return="void" name="enqueue">
     <param type="java.lang.Object" name="item"/>
	<param type="FifoImpl" name="fifo"/>
      <code>
	fifo.queue.add(item);
      </code>
    </method>

    <method modifiers="public" return="java.lang.Object" name="dequeue">
<param type="FifoImpl" name="fifo"/>
	<code>
		Object o;
		if (!fifo.queue.isEmpty()) 
			o = fifo.queue.remove();
		return o;
	</code>
     </method>
  </role>
  <!-- ====================================================================== -->
 <role name="ReceiverImpl" type="class" modifiers="public">
 <import type="org.osoa.sca.annotations.*"/>
<annotation>@Service(Receiver.class)</annotation> 
    <interface type="$Receiver$"/>

    <field modifiers="protected" type="$FifoDequeue$" name="fifodequeue">
      <comment>
        identify the dependency on Fifo service
      </comment>
 <annotation>@Reference</annotation>  
    </field>

   <constructor modifiers="public">
      <comment>Constructor</comment>
      <code>
        super();
      </code>
    </constructor>

    <method modifiers="public" return="void" name="dequeue">
<param type="FifoImpl" name="fifo"/>
      <code>
	Object o=fifodequeue.dequeue(fifo);
		doSomething(o);
      </code>
    </method>

 <method modifiers="private" return="void" name="doSomething">
<param type="java.lang.Object" name="o"/>
      <code>
	//TODO write your algoritm here....
      </code>
    </method>
   </role>
</templates>

=== stevencapelli/SCA-PatternBOX/editor-plugin/template.java/mediator.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE templates SYSTEM "templates.dtd">

<!-- Copyright (C) 2003-2012 by Dirk Ehms, www.patternbox.com. All rights reserved. -->

<templates id="mediator" version="1.0">

  <!-- ====================================================================== -->
  <role name="Mediator" type="interface" modifiers="public">

    <method modifiers="public" return="void" name="createColleagues">
      <comment>
        This method creates all colleagues instances.
      </comment>
    </method>

    <method modifiers="public" return="void" name="colleagueChanged">
      <comment>
        Each associated colleague have to call this method if its properties of
        interest are changed.
      </comment>
      <param type="$Colleague$" name="colleague" />
    </method>

  </role>

  <!-- ====================================================================== -->
  <role name="ConcreteMediator" type="class" modifiers="public">

    <interface type="$Mediator$"/>

    <method modifiers="public" return="void" name="createColleagues">
      <comment>
        This method creates all colleagues instances.
      </comment>
      <code>
      </code>
    </method>

    <method modifiers="public" return="void" name="colleagueChanged">
      <comment>
        Each associated colleague have to call this method if its properties of
        interest are changed.
      </comment>
      <param type="$Colleague$" name="colleague" />
      <code>
        // TODO Inform all other colleagues that one colleague has changed.
      </code>
    </method>

  </role>

  <!-- ====================================================================== -->
  <role name="Colleague" type="class" modifiers="public abstract">

    <field modifiers="private final" type="$Mediator$" name="fMediator">
      <comment>stores the associated Mediator</comment>
    </field>

    <constructor modifiers="public">
      <comment>Constructor</comment>
      <param type="$Mediator$" name="mediator" />
      <code>
        super();
        fMediator = mediator;
      </code>
    </constructor>

	<!--
    <method modifiers="protected" return="$Mediator$" name="getMediator">
      <comment>
        This method returns the associated Mediator instance to its derived classes.
      </comment>
      <code>return fMediator;</code>
    </method>
    -->

    <method modifiers="protected" return="void" name="changed">
      <comment>
      	Call this method from derived classes if a property of interest has been changed.
      </comment>
      <code>
        fMediator.colleagueChanged(this);
      </code>
    </method>

  </role>

  <!-- ====================================================================== -->
  <role name="ConcreteColleague" type="class" modifiers="public">

    <superclass type="$Colleague$"/>

    <constructor modifiers="public">
      <comment>Constructor</comment>
      <param type="$Mediator$" name="mediator" />
      <code>
        // call inherited constructor
        super(mediator);
      </code>
    </constructor>

  </role>

</templates>

=== stevencapelli/SCA-PatternBOX/editor-plugin/template.java/Router.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE templates SYSTEM "templates.dtd">

<!-- Copyright (C) 2003-2012 by Dirk Ehms, www.patternbox.com. All rights reserved. -->

<templates id="PatternRouter" version="1.1">

  <!-- ====================================================================== -->
  <role name="CustomerService" type="interface" modifiers="public">
   
 <method modifiers="public" return="void" name="send">
 
<param type="Object" name="o"/>
</method>
 </role>

<!-- ====================================================================== -->
 <role name="RouterService" type="interface" modifiers="public">
 <method modifiers="public" return="void" name="routing">
 <annotation>@OneWay</annotation> 
<param type="java.lang.Object" name="o"/>
</method>

</role>

<!-- ====================================================================== -->
 <role name="Service1" type="interface" modifiers="public">
 <import type="org.osoa.sca.annotations.*"/>
 <method modifiers="public" return="void" name="executeService">
<annotation>@OneWay</annotation> 
<param type="java.lang.Object" name="o"/>
</method>

</role>

<!-- ====================================================================== -->
 <role name="Service2" type="interface" modifiers="public">
 <import type="org.osoa.sca.annotations.*"/>
 <method modifiers="public" return="void" name="executeService">
<annotation>@OneWay</annotation> 
<param type="java.lang.Object" name="o"/>
</method>

</role>

<!-- ====================================================================== -->
 <role name="Service3" type="interface" modifiers="public">
 <import type="org.osoa.sca.annotations.*"/>
 <method modifiers="public" return="void" name="executeService">
<annotation>@OneWay</annotation> 
<param type="java.lang.Object" name="o"/>
</method>

</role>

<!-- ====================================================================== -->
 <role name="Customer" type="class" modifiers="public">
 <import type="org.osoa.sca.annotations.*"/>
<annotation>@Service(CustomerService.class)</annotation>   
<interface type="$CustomerService$"/>

<field modifiers="protected" type="$RouterService$" name="routerService">
      <comment>
        identify the dependency on RouterService
      </comment>
 <annotation>@Reference</annotation>  
    </field>

   <constructor modifiers="public">
      <comment>Constructor</comment>
      <code>
        super();
      </code>
    </constructor>

    <method modifiers="public" return="void" name="send">
      
	<param type="Object" name="o"/>
	<comment>call RouteService</comment>
      <code>
	routerService.routing(o);
      </code>
    </method>
	
   </role>

  <!-- ====================================================================== -->
  
  <role name="Router" type="class" modifiers="public">
 <import type="org.osoa.sca.annotations.*"/>
<annotation>@Service(RouterService.class)</annotation>   
<interface type="$RouterService$"/>


<field modifiers="protected" type="$Service1$" name="service1">
      <comment>
        identify the dependency on Service1
      </comment>
 <annotation>@Reference</annotation>  
    </field>

    <field modifiers="protected" type="$Service2$" name="service2">
      <comment>
        identify the dependency on Service2
      </comment>
 <annotation>@Reference</annotation>  
    </field>

<field modifiers="protected" type="$Service3$" name="service3">
      <comment>
        identify the dependency on Service3
      </comment>
 <annotation>@Reference</annotation>  
    </field>

<field modifiers="protected" type="$String$" name="policy">
 <annotation>@Property</annotation>  
    </field>

   <constructor modifiers="public">
      <comment>Constructor</comment>
      <code>
        super();
      </code>
    </constructor>

    <method modifiers="public" return="void" name="routing">
      
	<param type="Object" name="o"/>
      <code>
	switch(policy){
	  case "service1":{
		  service1.executeService(o);
		  break;
	  }
	  case "service2":{
		  service2.executeService(o);
		  break;
	  }
	  case "service3":{
		  service3.executeService(o);
		  break;
	  }
	  default:
	  }
      </code>
    </method>

<method modifiers="publiic" return="String" name="getPolicy">
      <code>
	return this.policy;
      </code>
    </method>

<method modifiers="public" return="void" name="setPolicy">
      
	<param type="String" name="s"/>
      <code>
	this.policy=s;
      </code>
    </method>

   </role>
   
  <!-- ====================================================================== -->
  
  <role name="Service1Impl" type="class" modifiers="public">
 <import type="org.osoa.sca.annotations.*"/>
 <annotation>@Service(Service1.class)</annotation>   
<interface type="$Service1$"/>

   <constructor modifiers="public">
      <comment>Constructor</comment>
      <code>
        super();
      </code>
    </constructor>

    <method modifiers="public" return="void" name="executeService">
      <param type="Object" name="o"/>
      <comment>do something</comment>
    </method>

   </role>

<!-- ====================================================================== -->
  
  <role name="Service2Impl" type="class" modifiers="public">
 <import type="org.osoa.sca.annotations.*"/>
 <annotation>@Service(Service2.class)</annotation>   
<interface type="$Service2$"/>

   <constructor modifiers="public">
      <comment>Constructor</comment>
      <code>
        super();
      </code>
    </constructor>

    <method modifiers="public" return="void" name="executeService">
      <param type="Object" name="o"/>
      <comment>do something</comment>
    </method>

   </role>

<!-- ====================================================================== -->
  
  <role name="Service3Impl" type="class" modifiers="public">
 <import type="org.osoa.sca.annotations.*"/>
 <annotation>@Service(Service3.class)</annotation>   
<interface type="$Service3$"/>

   <constructor modifiers="public">
      <comment>Constructor</comment>
      <code>
        super();
      </code>
    </constructor>

    <method modifiers="public" return="void" name="executeService">
      <param type="Object" name="o"/>
      <comment>do something</comment>
    </method>

   </role>
</templates>

=== stevencapelli/SCA-PatternBOX/editor-plugin/template.java/adapter.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE templates SYSTEM "templates.dtd">

<!-- Copyright (C) 2003-2012 by Dirk Ehms, www.patternbox.com. All rights reserved. -->

<templates id="adapter" version="1.0">

  <!-- ====================================================================== -->
  <role name="Target" type="interface" modifiers="public" >

    <method modifiers="public" return="void" name="request">
      <comment>
      </comment>
    </method>

  </role>

  <!-- ====================================================================== -->
  <role name="Client" type="class" modifiers="public">

    <field modifiers="private final" type="$Target$" name="fTarget"/>

    <constructor modifiers="public">
      <param type="$Target$" name="target"/>
      <code>
        super();
        fTarget = target;
      </code>
    </constructor>

    <method modifiers="public" return="void" name="useAdapter">
      <comment>
        This is just an example how to use the Adapter pattern. This operation
        must be customized based on your application needs.
      </comment>
      <code>
        // TODO: Customize this method based on your application needs.
        fTarget.request();
      </code>
    </method>

  </role>

  <!-- ====================================================================== -->
  <role name="Adapter" type="class" modifiers="public">

    <interface type="$Target$"/>

    <field modifiers="private final" type="$Adaptee$" name="fAdaptee"/>

    <constructor modifiers="public">
      <param type="$Adaptee$" name="adaptee"/>
      <code>
        super();
        fAdaptee = adaptee;
      </code>
    </constructor>

    <method modifiers="public" return="void" name="request">
      <comment>
        This method adapts the Target to the Adaptee's specific method.
      </comment>
      <code>
        fAdaptee.specificRequest();
      </code>
    </method>

  </role>

  <!-- ====================================================================== -->
  <role name="Adaptee" type="class" modifiers="public">

    <method modifiers="public" return="void" name="specificRequest">
      <comment>This operation must be adapted by the Adapter.</comment>
      <code>
        // TODO: Customize this method based on your application needs.
      </code>
    </method>

  </role>

</templates>

=== stevencapelli/SCA-PatternBOX/editor-plugin/template.java/PingEchoHeartBeat.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE templates SYSTEM "templates.dtd">

<!-- Copyright (C) 2003-2012 by Dirk Ehms, www.patternbox.com. All rights reserved. -->

<templates id="pingechoheartbeat" version="1.1">

  <!-- ====================================================================== -->
  <role name="Sender" type="interface" modifiers="public">
   
 <method modifiers="public" return="void" name="run">
      <comment>
       This method declaration allows to run the Pattern and verifies that the Receiver is reachable.
      </comment>
    </method>
</role>

<!-- ====================================================================== -->
  <role name="Receiver" type="interface" modifiers="public">

    <method modifiers="public" return="long" name="request">
      <comment>
        This method receives a request and returns the timestamp of the request.
        Furthermore it verifies whether Serder is alive.
      </comment>
<param type="java.lang.Object" name="item"/>
    </method>
  </role>

  <!-- ====================================================================== -->
  <role name="SenderImpl" type="class" modifiers="public">
 <import type="org.osoa.sca.annotations.*"/>
<import type="java.util.Calendar"/>
<annotation>@Service(Sender.class)</annotation> 
    <interface type="$Sender$"/>

    <field modifiers="protected" type="$Receiver$" name="receiver">
      <comment>
        identify the dependency on Receiver's service
      </comment>
 <annotation>@Reference</annotation>  
    </field>

   <constructor modifiers="public">
      <comment>Constructor</comment>
      <code>
        super();
      </code>
    </constructor>

    <method modifiers="public" return="void" name="run">
      <code>
  doSomething(items);      
	long time=Calendar.getInstance().getTimeInMillis();
  long beatTime=Calendar.getInstance().getTimeInMillis();
	long timeReturn=Calendar.getInstance().getTimeInMillis();
  return beatTime;
	//TODO Write your algorithm here...      
	</code>
    </method>
    <method modifiers="private" return="void" name="doSomething">
     <param type="java.lang.Object" name="items"/>
      <code>
  //TODO Write your algorithm here....
      </code>
    </method>
</role>

  
  <!-- ====================================================================== -->
  <role name="ReceiverImpl" type="class" modifiers="public">
 <import type="org.osoa.sca.annotations.*"/>
<import type="java.util.Calendar"/>
 <annotation>@Service(Receiver.class)</annotation> 
    <interface type="$Receiver$"/>
   
<constructor modifiers="public">
      <comment>Constructor</comment>
      <code>
        super();
      </code>
    </constructor>
   <method modifiers="public" return="long" name="request">
     <param type="java.lang.Object" name="items"/>
      <code>
	doSomething(items);
  long maxWaitingTime;
  long beatTime=Calendar.getInstance().getTimeInMillis();
	long time=Calendar.getInstance().getTimeInMillis();
	return time;
      </code>
    </method>
<method modifiers="private" return="void" name="doSomething">
     <param type="java.lang.Object" name="items"/>
      <code>
	//TODO Write your algorithm here....
      </code>
    </method>
</role>
</templates>

=== stevencapelli/SCA-PatternBOX/editor-plugin/template.java/memento.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE templates SYSTEM "templates.dtd">

<!-- Copyright (C) 2003-2012 by Dirk Ehms, www.patternbox.com. All rights reserved. -->

<templates id="memento" version="1.0">

  <!-- ====================================================================== -->
  <role name="Memento" type="class" modifiers="public">

    <field modifiers="private" type="$State$" name="fState">
      <comment>stores the State instance of the Memento</comment>
    </field>

    <constructor modifiers="public">
      <comment>Default constructor</comment>
      <code>
        super();
      </code>
    </constructor>

    <constructor modifiers="public">
      <comment>Constructor</comment>
      <param type="$State$" name="state" />
      <code>
        super();
        fState = state;
      </code>
    </constructor>

    <method modifiers="public" return="void" name="setState">
      <comment>
        This method stores a State instance.
      </comment>
      <param type="$State$" name="state" />
      <code>
        fState = state;
      </code>
    </method>

    <method modifiers="public" return="$State$" name="getState">
      <comment>
        This method returns the associated State instance.
      </comment>
      <code>
        return fState;
      </code>
    </method>

  </role>

  <!-- ====================================================================== -->
  <role name="Originator" type="class" modifiers="public" >

    <field modifiers="private" type="$State$" name="fState">
      <comment>stores the internal state of the Originator</comment>
    </field>

    <constructor modifiers="public">
      <comment>Default constructor</comment>
      <code>
        super();
      </code>
    </constructor>

    <constructor modifiers="public">
      <comment>Constructor</comment>
      <param type="$State$" name="state" />
      <code>
        super();
        fState = state;
      </code>
    </constructor>

    <method modifiers="public" return="$Memento$" name="createMemento">
      <comment>
        This method creates and returns a Memento object containing a snapshot
        of the Originator instance's state.
      </comment>
      <code>
        return new Memento(fState);
      </code>
    </method>

    <method modifiers="public" return="void" name="setMemento">
      <comment>
        This method passes back a Memento object to an Originator instance. The
        Memento object must be used to restore an earlier Originator state.
      </comment>
      <param type="$Memento$" name="memento" />
      <code>
        fState = memento.getState();
      </code>
    </method>

  </role>

  <!-- ====================================================================== -->
  <role name="Caretaker" type="class" modifiers="public" >

    <import type="java.util.Stack"/>

    <field modifiers="private final" type="java.util.Stack" name="fHistoryStack" initial="new Stack()">
      <comment>Stores a list of history states.</comment>
    </field>

    <field modifiers="private final" type="$Originator$" name="fOriginator">
      <comment>Stores the associated Originator instance.</comment>
    </field>

    <constructor modifiers="public">
      <comment>Default constructor</comment>
      <param type="$Originator$" name="originator" />
      <code>
        super();
        fOriginator = originator;
      </code>
    </constructor>

    <method modifiers="public" return="void" name="backupState">
      <comment>
        This method backups the current Originator state and stores it in a
        history stack. This snapshot can be used to restore the current state
        later.
      </comment>
      <code>
        fHistoryStack.push(fOriginator.createMemento());
      </code>
    </method>

    <method modifiers="public" return="boolean" name="restoreState">
      <comment>
        This method restores a previous Originator state.
      </comment>
      <code>
        // check whether snapshots available
        if (!fHistoryStack.empty()) {
          $Memento$ memento = ($Memento$) fHistoryStack.pop();
          fOriginator.setMemento(memento);
          return true;
        } else {
          return false;
        }  // if - else
      </code>
    </method>

  </role>

  <!-- ====================================================================== -->
  <role name="State" type="interface" modifiers="public" >

  </role>

</templates>
