=== stevencapelli/SCA-PatternBOX/editor-plugin/template.java/templates.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- 
  
  Copyright (C) 2003-2012 by Dirk Ehms, www.patternbox.com. 
  All rights reserved. 
  
  This DTD module is identified by the SYSTEM identifier:
  SYSTEM "templates.dtd"

  Version: 1.0
  Date:    2003-09-02

-->

<!ELEMENT templates (role*)>
<!ATTLIST templates
  id        NMTOKEN   #REQUIRED
  version   NMTOKEN   #REQUIRED
>

<!ELEMENT role (import*,annotation?,superclass?,interface*,field*,constructor*,method*)>
<!ATTLIST role
  name      ID                 #REQUIRED
  type      (class|interface|enum)  #REQUIRED
  modifiers CDATA              #IMPLIED
>

<!ELEMENT import EMPTY>
<!ATTLIST import
  type      CDATA   #REQUIRED
>

<!ELEMENT superclass EMPTY>
<!ATTLIST superclass
  type      CDATA   #REQUIRED
>

<!ELEMENT interface EMPTY>
<!ATTLIST interface
  type      CDATA   #REQUIRED
>

<!ELEMENT field (comment?, annotation?)>
<!ATTLIST field
  modifiers CDATA   #IMPLIED
  type      CDATA   #REQUIRED
  name      CDATA   #REQUIRED
  initial   CDATA   #IMPLIED
>

<!ELEMENT constructor (comment?,annotation?,param*,exception*,code?)>
<!ATTLIST constructor
  modifiers CDATA #IMPLIED
>

<!ELEMENT method (comment?,annotation?,param*,exception*,code?)>
<!ATTLIST method
  modifiers CDATA   #IMPLIED
  return    CDATA   #REQUIRED
  name      CDATA   #REQUIRED
  foreach   CDATA   #IMPLIED
>

<!ELEMENT param (comment?)>
<!ATTLIST param
  type      CDATA   #REQUIRED
  name      CDATA   #REQUIRED
>

<!ELEMENT exception EMPTY>
<!ATTLIST exception
  type      CDATA   #REQUIRED
>

<!ELEMENT comment (#PCDATA)>

<!ELEMENT annotation (#PCDATA)>

<!ELEMENT code (#PCDATA|replace)*>

<!ELEMENT replace (#PCDATA)>
<!ATTLIST replace
  initial     CDATA   #REQUIRED
  dependence  IDREF   #REQUIRED
>

=== stevencapelli/SCA-PatternBOX/editor-plugin/template.java/builder.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE templates SYSTEM "templates.dtd">

<!-- Copyright (C) 2003-2012 by Dirk Ehms, www.patternbox.com. All rights reserved. -->

<templates id="builder" version="1.0">

  <!-- ====================================================================== -->
  <role name="Builder" type="interface" modifiers="public">

    <method modifiers="public" return="void" name="buildPartA">
      <comment>
        This method constructs and assembles a particular part of a Product.
      </comment>
    </method>

    <method modifiers="public" return="void" name="buildPartB">
      <comment>
        This method constructs and assembles a particular part of a Product.
      </comment>
    </method>

  </role>

  <!-- ====================================================================== -->
  <role name="ConcreteBuilder" type="class" modifiers="public" >

    <interface type="$Builder$"/>

    <field modifiers="private final" type="$Product$" name="fProduct" initial="new $Product$()">
      <comment>stores the Product instance of the ConcreteBuilder</comment>
    </field>

    <constructor modifiers="public">
      <comment>
        This construtor creates a ConcreteBuilder instance.
      </comment>
      <code>
        super();
      </code>
    </constructor>

    <method modifiers="public" return="void" name="buildPartA">
      <comment>
        This method constructs and assembles a particular part of a Product.
      </comment>
      <code>
        // TODO: Customize this method based on your application needs.
      </code>
    </method>

    <method modifiers="public" return="void" name="buildPartB">
      <comment>
        This method constructs and assembles a particular part of a Product.
      </comment>
      <code>
        // TODO: Customize this method based on your application needs.
      </code>
    </method>

    <method modifiers="public" return="$Product$" name="getProduct">
      <comment>
        This method returns the Product instance.
      </comment>
      <code>
        return fProduct;
      </code>
    </method>

  </role>

  <!-- ====================================================================== -->
  <role name="Director" type="class" modifiers="public" >

    <field modifiers="private final" type="$Builder$" name="fBuilder">
      <comment>Stores the Builder instance of the Director</comment>
    </field>

    <constructor modifiers="public">
      <comment>
        This construtor creates a Director instance.
        @param builder Concrete Builder implementation.
      </comment>
      <param type="$Builder$" name="builder" />
      <code>
        super();
        fBuilder = builder;
      </code>
    </constructor>

    <method modifiers="public" return="void" name="construct">
      <comment>
        This method constructs an object by using the Builder interface.
      </comment>
      <code>
        // TODO: Customize this method based on your application needs.
        fBuilder.buildPartA();
        fBuilder.buildPartB();
      </code>
    </method>

  </role>

  <!-- ====================================================================== -->
  <role name="Product" type="class" modifiers="public" >

    <constructor modifiers="public">
      <comment>
        This construtor creates a Product instance.
      </comment>
      <code>
        super();
      </code>
    </constructor>

  </role>

  <!-- ====================================================================== -->
  <role name="Client" type="class" modifiers="public" >

    <constructor modifiers="public">
      <comment>
        This construtor creates a Client instance.
      </comment>
      <code>
        super();
      </code>
    </constructor>

    <method modifiers="public" return="$Product$" name="use$ConcreteBuilder$" foreach="ConcreteBuilder">
      <comment>
        This is just an example how to use the ConcreteBuilder pattern. This
        method must be customized based on your application needs.
      </comment>
      <code>
        final $ConcreteBuilder$ concreteBuilder = new $ConcreteBuilder$();
        final $Director$ director = new $Director$(concreteBuilder);
        director.construct();
        return concreteBuilder.getProduct();
      </code>
    </method>

  </role>

</templates>

=== stevencapelli/SCA-PatternBOX/editor-plugin/template.java/factorymethod.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE templates SYSTEM "templates.dtd">

<!-- Copyright (C) 2003-2012 by Dirk Ehms, www.patternbox.com. All rights reserved. -->

<templates id="factorymethod" version="1.1">

  <!-- ====================================================================== -->
  <role name="Product" type="interface" modifiers="public">

  </role>

  <!-- ====================================================================== -->
  <role name="ConcreteProduct" type="class" modifiers="public">

    <interface type="$Product$"/>

    <constructor modifiers="public">
      <comment>Default constructor</comment>
      <code>
        super();
      </code>
    </constructor>

  </role>

  <!-- ====================================================================== -->
  <role name="Creator" type="class" modifiers="public abstract">

    <field modifiers="private" type="$Product$" name="fProduct">
      <comment>stores the Creator instance of the Product</comment>
    </field>

    <method modifiers="public abstract" return="$Product$" name="factoryMethod">
      <comment>
        The ConcreteCreator implementation have to return a ConcreteProduct.
      </comment>
    </method>

    <method modifiers="public" return="void" name="anOperation">
      <comment>
        This method invokes the ConcreteCreator implementation to create a
        ConcreteProduct.
      </comment>
      <code>
        fProduct = factoryMethod();
      </code>
    </method>

  </role>

  <!-- ====================================================================== -->
  <role name="ConcreteCreator" type="class" modifiers="public">

    <superclass type="$Creator$"/>

    <constructor modifiers="public">
      <comment>Default constructor</comment>
      <code>
        super();
      </code>
    </constructor>

    <method modifiers="public" return="$Product$" name="factoryMethod">
      <comment>
        This method returns a new instance of a ConcreteProduct implementation.
      </comment>
      <code>
        return new $ConcreteProduct$();
      </code>
    </method>

  </role>

</templates>

=== stevencapelli/SCA-PatternBOX/editor-plugin/template.java/composite.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE templates SYSTEM "templates.dtd">

<!-- Copyright (C) 2003-2012 by Dirk Ehms, www.patternbox.com. All rights reserved. -->

<templates id="composite" version="1.0">

  <!-- ====================================================================== -->
  <role name="Component" type="class" modifiers="public abstract">

    <method modifiers="public abstract" return="void" name="operation">
      <comment>
        This method is the implementation of Component specific operation.
      </comment>
    </method>

    <method modifiers="public abstract" return="void" name="add">
      <comment>
        This method adds a new child (either Leaf or Composite) to the other children.
      </comment>
      <param type="$Component$" name="child" />
      <exception type="java.lang.AbstractMethodError"/>
    </method>

    <method modifiers="public abstract" return="void" name="remove">
      <comment>
        This method removes a child (either Leaf or Composite) from the children.
      </comment>
      <param type="$Component$" name="child" />
      <exception type="java.lang.AbstractMethodError"/>
    </method>

    <method modifiers="public abstract" return="$Component$" name="getChild">
      <comment>
        This method returns a child (either Leaf or Composite) at a certain index.
      </comment>
      <param type="int" name="index" />
      <exception type="java.lang.AbstractMethodError"/>
    </method>

  </role>

  <!-- ====================================================================== -->
  <role name="Leaf" type="class" modifiers="public" >

    <superclass type="$Component$"/>

    <field modifiers="private final static"
    	   type="java.lang.String"
    	   name="ERROR_MSG"
    	   initial="&quot;This method should never be called.&quot;">
      <comment>Error message constant</comment>
    </field>

    <method modifiers="public" return="void" name="operation">
      <comment>
        This method is the implementation of Leaf specific operation.
      </comment>
      <code>
        // TODO Write your specific operation code here ...
      </code>
    </method>

    <method modifiers="public" return="void" name="add">
      <comment>
        This method should never be called, otherwise an AbstractMethodError
        will be thrown.
      </comment>
      <param type="$Component$" name="child" />
      <exception type="java.lang.AbstractMethodError"/>
      <code>
      	throw new AbstractMethodError(ERROR_MSG);
      </code>
    </method>

    <method modifiers="public" return="void" name="remove">
      <comment>
        This method should never be called, otherwise an AbstractMethodError
        will be thrown.
      </comment>
      <param type="$Component$" name="child" />
      <exception type="java.lang.AbstractMethodError"/>
      <code>
      	throw new AbstractMethodError(ERROR_MSG);
      </code>
    </method>

    <method modifiers="public" return="$Component$" name="getChild">
      <comment>
        This method should never be called, otherwise an AbstractMethodError
        will be thrown.
      </comment>
      <param type="int" name="index" />
      <exception type="java.lang.AbstractMethodError"/>
      <code>
      	throw new AbstractMethodError(ERROR_MSG);
      </code>
    </method>

  </role>

  <!-- ====================================================================== -->
  <role name="Composite" type="class" modifiers="public" >

  	<import type="java.util.ArrayList"/>
  	<import type="java.util.Iterator"/>

    <superclass type="$Component$"/>

    <field modifiers="private final" type="java.util.List" name="fChildren" initial="new ArrayList()">
      <comment>Collection of children in the Composite hierachy</comment>
    </field>

    <method modifiers="public" return="void" name="operation">
      <comment>
        This method iterates of all Component children specific operations.
      </comment>
      <code>
        Iterator iterator = fChildren.iterator();
        while (iterator.hasNext()) {
           ((Component) iterator.next()).operation();
        }  // while
      </code>
    </method>

    <method modifiers="public" return="void" name="add">
      <comment>
        This method adds a new child (either Leaf or Composite) to the other children.
      </comment>
      <param type="$Component$" name="child" />
      <exception type="java.lang.AbstractMethodError"/>
      <code>
      	fChildren.add(child);
      </code>
    </method>

    <method modifiers="public" return="void" name="remove">
      <comment>
        This method removes a child (either Leaf or Composite) from the children.
      </comment>
      <param type="$Component$" name="child" />
      <exception type="java.lang.AbstractMethodError"/>
      <code>
      	fChildren.remove(child);
      </code>
    </method>

    <method modifiers="public" return="$Component$" name="getChild">
      <comment>
        This method returns a child (either Leaf or Composite) at a certain index.
      </comment>
      <param type="int" name="index" />
      <exception type="java.lang.AbstractMethodError"/>
      <code>
      	return ($Component$) fChildren.get(index);
      </code>
    </method>

  </role>

  <!-- ====================================================================== -->
  <role name="Client" type="class" modifiers="public" >

    <field modifiers="private" type="$Component$" name="fComponent" initial="null">
      <comment>stores the Command instance of the Invoker</comment>
    </field>

    <constructor modifiers="public">
      <comment>
        Default construtor
      </comment>
      <code>
        super();
      </code>
    </constructor>

    <constructor modifiers="public">
      <comment>
        This construtor overloads the default constructor. An instance
        of Component is delivered as parameter.
      </comment>
      <param type="$Component$" name="component" />
      <code>
        super();
        fComponent = component;
      </code>
    </constructor>

    <method modifiers="public" return="void" name="createComposite">
      <comment>
        This method shows an example how to create a simple composite hierarchy.
      </comment>
      <code>
      	fComponent = new $Composite$();

      	$Composite$ composite = new $Composite$();
      	composite.add(new $Leaf$());
      	composite.add(new $Leaf$());

      	fComponent.add(composite);
      	fComponent.add(new $Leaf$());
      </code>
    </method>

    <method modifiers="public" return="void" name="useComposite">
      <comment>
        This method invokes the specific Component operation.
      </comment>
      <code>
      	fComponent.operation();
      </code>
    </method>

  </role>

</templates>

=== stevencapelli/SCA-PatternBOX/editor-plugin/template.java/requestresponse.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE templates SYSTEM "templates.dtd">

<!-- Copyright (C) 2003-2012 by Dirk Ehms, www.patternbox.com. All rights reserved. -->

<templates id="requestresponse" version="1.0">

  <!-- ====================================================================== -->
  <role name="Requestresponse" type="interface" modifiers="public">
 <import type="org.osoa.sca.annotations.*"/>
    <method modifiers="public" return="java.lang.Object" name="requestresponse">
 
 <comment>
        This method declaration must be implemented by the Server implementations.
      </comment>
<param type="java.lang.Object" name="item"/>
    </method>

  </role>

  <!-- ====================================================================== -->
  <role name="ServerImpl" type="class" modifiers="public" >
<import type="org.osoa.sca.annotations.*"/>
<annotation>@Service(Requestresponse.class)</annotation>
    <interface type="$Requestresponse$"/>
  
    <constructor modifiers="public">
      <comment>Default constructor</comment>
      <code>
        super();
      </code>
    </constructor>

    <method modifiers="public" return="java.lang.Object" name="requestresponse">
      <comment>
        This method implements the service operation declared in the RequestResponse interface.
      </comment>
	<param type="java.lang.Object" name="item"/>
      <code>
        // TODO Write your algorithm code here ...
	return item;
      </code>
    </method>

  </role>

  <!-- ====================================================================== -->
  <role name="ClientRequestresponseImpl" type="class" modifiers="public" >
<import type="org.osoa.sca.annotations.*"/>
  <annotation>@Service(Runnable.class)</annotation>
<interface type="java.lang.Runnable"/>
    <field modifiers="protected" type="$Requestresponse$" name="fRequestresponse">
      <comment>the reference to a requestresponse service. </comment>
<annotation>@Reference</annotation>  
    </field>

    <constructor modifiers="public">
      <comment>Constructor</comment>
      <param type="$Requestresponse$" name="requestresponse" />
      <code>
        super();
      </code>
    </constructor>

    <method modifiers="public" return="void" name="run">
      <code>
	Object item;
        Object items = fRequestresponse.requestresponse(item);
	// TODO Write your algorithm code here ...
      </code>
    </method>

  </role>

</templates>

=== stevencapelli/SCA-PatternBOX/editor-plugin/template.java/abstractfactory.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE templates SYSTEM "templates.dtd">

<!-- Copyright (C) 2003-2012 by Dirk Ehms, www.patternbox.com. All rights reserved. -->

<templates id="abstractfactory" version="1.0">

  <!-- ====================================================================== -->
  <role name="AbstractFactory" type="interface" modifiers="public">

    <method modifiers="public" return="$AbstractProduct$" name="create$ConcreteProduct$" foreach="ConcreteProduct" >
      <comment>
        This method returns an instance of a AbstractProduct implementation
      </comment>
    </method>

  </role>

  <!-- ====================================================================== -->
  <role name="ConcreteFactory" type="class" modifiers="public">

    <interface type="$AbstractFactory$"/>

    <constructor modifiers="public">
      <comment>
        This construtor creates a ConcreteFactory instance.
      </comment>
      <code>super();</code>
    </constructor>

    <method modifiers="public" return="$AbstractProduct$" name="create$ConcreteProduct$" foreach="ConcreteProduct" >
      <comment>
        This method returns an instance of a AbstractProduct implementation
      </comment>
      <code>return new $ConcreteProduct$();</code>
    </method>

  </role>

  <!-- ====================================================================== -->
  <role name="AbstractProduct" type="interface" modifiers="public">

    <method modifiers="public" return="void" name="doSomething">
      <comment>
        This is just a dummy method that can be called by the client. Replace
        this method by another one which you really need.
      </comment>
    </method>

  </role>

  <!-- ====================================================================== -->
  <role name="ConcreteProduct" type="class" modifiers="public">

    <interface type="$AbstractProduct$"/>

    <constructor modifiers="public">
      <comment>
        This construtor creates a ConcreteProduct instance.
      </comment>
      <code>super();</code>
    </constructor>

    <method modifiers="public" return="void" name="doSomething">
      <comment>
        This is just a dummy method that can be called by the client. Replace
        this method by another one which you really need.
      </comment>
      <code/>
    </method>

  </role>

  <!-- ====================================================================== -->
  <role name="Client" type="class" modifiers="public">

    <field modifiers="private final" type="$AbstractFactory$" name="fFactory">
      <comment>holds the factory instance</comment>
    </field>

    <constructor modifiers="public">
      <comment>
        This construtor creates a Client instance.
      </comment>
      <param type="$AbstractFactory$" name="factory" />
      <code>
        super();
        fFactory = factory;
      </code>
    </constructor>

    <method modifiers="public" return="void" name="use$ConcreteProduct$" foreach="ConcreteProduct">
      <comment>
        This is just an example how to use the Abstract Factory pattern. This
        operation must be customized based on your application needs.
      </comment>
      <code>
        // TODO: Customize this method based on your application needs.
        final $AbstractProduct$ product = fFactory.create$ConcreteProduct$();
        product.doSomething();
      </code>
    </method>

  </role>

</templates>

=== stevencapelli/SCA-PatternBOX/editor-plugin/template.java/strategy.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE templates SYSTEM "templates.dtd">

<!-- Copyright (C) 2003-2012 by Dirk Ehms, www.patternbox.com. All rights reserved. -->

<templates id="strategy" version="1.0">

  <!-- ====================================================================== -->
  <role name="Strategy" type="interface" modifiers="public">

    <method modifiers="public" return="void" name="algorithmInterface">
      <comment>
        This method declaration must be implemented by the ConcreteStrategy implementations.
      </comment>
    </method>

  </role>

  <!-- ====================================================================== -->
  <role name="ConcreteStrategy" type="class" modifiers="public" >

    <interface type="$Strategy$"/>

    <constructor modifiers="public">
      <comment>Default constructor</comment>
      <code>
        super();
      </code>
    </constructor>

    <method modifiers="public" return="void" name="algorithmInterface">
      <comment>
        This method implements the algorithm operation defined by the Strategy interface.
      </comment>
      <code>
        // TODO Write your algorithm code here ...
      </code>
    </method>

  </role>

  <!-- ====================================================================== -->
  <role name="Context" type="class" modifiers="public" >

    <field modifiers="private final" type="$Strategy$" name="fStrategy">
      <comment>stores the Strategy instance of the Context</comment>
    </field>

    <constructor modifiers="public">
      <comment>Constructor</comment>
      <param type="$Strategy$" name="strategy" />
      <code>
        super();
        fStrategy = strategy;
      </code>
    </constructor>

    <method modifiers="public" return="void" name="contextInterface">
      <comment>
        This method invokes the algorithm interface of the current Strategy
      </comment>
      <code>
        fStrategy.algorithmInterface();
      </code>
    </method>

  </role>

</templates>

=== stevencapelli/SCA-PatternBOX/editor-plugin/template.java/command.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE templates SYSTEM "templates.dtd">

<!-- Copyright (C) 2003-2012 by Dirk Ehms, www.patternbox.com. All rights reserved. -->

<templates id="command" version="1.0.1">

  <!-- ====================================================================== -->
  <role name="Command" type="interface" modifiers="public">

    <method modifiers="public" return="void" name="execute">
      <comment>
        This abstract method must be implemented by the ConcreteCommand implementation.
      </comment>
    </method>

  </role>

  <!-- ====================================================================== -->
  <role name="ConcreteCommand" type="class" modifiers="public" >

    <interface type="$Command$"/>

    <field modifiers="private final" type="$Receiver$" name="fReceiver">
      <comment>stores the Receiver instance of the ConcreteCommand</comment>
    </field>

    <constructor modifiers="public">
      <comment>Constructor</comment>
      <!--<param type="$State$" name="state" />-->
      <param type="$Receiver$" name="receiver" />
      <code>
        super();
        fReceiver = receiver;
      </code>
    </constructor>

    <method modifiers="public" return="void" name="execute">
      <comment>
        This method executes the command by invoking the corresponding
        method of the Receiver instance.
      </comment>
      <code>
        fReceiver.action();
      </code>
    </method>

  </role>

  <!-- ====================================================================== -->
  <role name="Client" type="class" modifiers="public" >

    <field modifiers="private final" type="$Receiver$" name="fReceiver">
      <comment>stores the Receiver instance of the Client</comment>
    </field>

    <constructor modifiers="public">
      <comment>
        This construtor creates a Client instance and stores the given Receiver.
      </comment>
      <param type="$Receiver$" name="receiver" />
      <code>
        super();
        fReceiver = receiver;
      </code>
    </constructor>

    <method modifiers="public" return="void" name="init$ConcreteCommand$" foreach="ConcreteCommand">
      <comment>
        This method creates a ConcreteCommand instance and specifies a Receiver object.
      </comment>
      <code>
        $ConcreteCommand$ cmd = new $ConcreteCommand$(fReceiver);
        $Invoker$ invoker = new $Invoker$();
        invoker.storeCommand(cmd);
      </code>
    </method>

  </role>

  <!-- ====================================================================== -->
  <role name="Invoker" type="class" modifiers="public" >

    <field modifiers="private" type="$Command$" name="fCommand">
      <comment>stores the Command instance of the Invoker</comment>
    </field>

    <constructor modifiers="public">
      <comment>Default constructor</comment>
      <code>
        super();
      </code>
    </constructor>

    <constructor modifiers="public">
      <comment>Constructor</comment>
      <param type="$Command$" name="cmd" />
      <code>
        super();
        fCommand = cmd;
      </code>
    </constructor>

    <method modifiers="public" return="void" name="storeCommand">
      <comment>
        This method stores a ConcreteCommand instance.
      </comment>
      <param type="$Command$" name="cmd" />
      <code>
        fCommand = cmd;
      </code>
    </method>

    <method modifiers="public" return="void" name="execute">
      <comment>
        This method performs the actions associated with the ConcreteCommand
        instance.
      </comment>
      <code>
        fCommand.execute();
      </code>
    </method>

  </role>

  <!-- ====================================================================== -->
  <role name="Receiver" type="class" modifiers="public" >

    <constructor modifiers="public">
      <comment>
        This construtor creates a Receiver instance.
      </comment>
      <code>
        super();
      </code>
    </constructor>

    <method modifiers="public" return="void" name="action">
      <comment>
        This method performs an action.
      </comment>
      <code>
        // TODO Write your action code here ...
      </code>
    </method>

  </role>

</templates>
