=== stevencapelli/SCA-PatternBOX/editor-plugin/pattern.mf/manifest.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- 
  
  Copyright (C)2003-2012 by Dirk Ehms, www.patternbox.com. 
  All rights reserved. 
  
  This DTD module is identified by the SYSTEM identifier:
  SYSTEM "manifest.dtd"

  Version: 1.1
  Date:    2003-09-23

-->

<!ELEMENT pattern (comment,role+)>
<!ATTLIST pattern
  id            NMTOKEN   #REQUIRED
  name          CDATA     #REQUIRED
  topCategorie  CDATA     #REQUIRED
  subCategorie  CDATA     #IMPLIED
  authorName    CDATA     "Dirk Ehms"
  authorWebsite CDATA     "www.patternbox.com"
>

<!-- design pattern participant -->
<!ELEMENT role (comment,dependence?)>
<!ATTLIST role
  name          ID        #REQUIRED
  min           NMTOKEN   #REQUIRED
  max           NMTOKEN   #REQUIRED
>

<!-- role dependence -->
<!ELEMENT dependence EMPTY>
<!ATTLIST dependence
  roles         IDREFS    #REQUIRED
>

<!-- pattern|role comment -->
<!ELEMENT comment (#PCDATA|li)*>

<!-- comment list item -->
<!ELEMENT li (#PCDATA)>

=== stevencapelli/SCA-PatternBOX/editor-plugin/pattern.mf/abstractfactory.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE pattern SYSTEM "manifest.dtd">
<pattern id="abstractfactory"
         name="Abstract Factory"
         topCategorie="GoF"
         subCategorie="Creational Pattern">

  <comment>
    Provide an interface for creating families of related or dependent objects without specifying their concrete classes.
  </comment>

  <!-- ====================================================================== -->
  <role name="AbstractFactory" min="1" max="1">
    <comment>
      <li>declares an interface for operations that create abstract product objects.</li>
    </comment>
    <dependence roles="ConcreteProduct" />
  </role>

  <!-- ====================================================================== -->
  <role name="ConcreteFactory" min="1" max="1">
    <comment>
      <li>implements the operations to create concrete product objects.</li>
    </comment>
    <dependence roles="AbstractFactory" />
  </role>

  <!-- ====================================================================== -->
  <role name="AbstractProduct" min="1" max="1">
    <comment>
      <li>declares an interface for a type of product object.</li>
    </comment>
  </role>

  <!-- ====================================================================== -->
  <role name="ConcreteProduct" min="1" max="n">
    <comment>
      <li>defines a product object to be created by the corresponding concrete factory.</li>
      <li>implements the AbstractProduct interface.</li>
    </comment>
    <dependence roles="AbstractProduct" />
  </role>

  <!-- ====================================================================== -->
  <role name="Client" min="1" max="n">
    <comment>
      <li>uses only interfaces declared by AbstractFactory and AbstractProduct classes.</li>
    </comment>
    <dependence roles="AbstractFactory AbstractProduct" />
  </role>

</pattern>

=== stevencapelli/SCA-PatternBOX/editor-plugin/pattern.mf/oneway.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE pattern SYSTEM "manifest.dtd">
<pattern id="oneway"
         name="Oneway"
         topCategorie="SCA"
         subCategorie="Micro Pattern">

  <comment>
   Micropattern. Define a type of interaction where the calling component uses an SCA reference proxy to send a message to another component and doesn't wait for a response.
  </comment>

  <!-- ====================================================================== -->
  <role name="Oneway" min="1" max="1">
    <comment>
      <li>defines an interface with one way services</li>
    </comment>
  </role>

  <!-- ====================================================================== -->
  <role name="ReceiverImpl" min="1" max="1">
    <comment>
      <li>implements the Oneway interface.</li>
    </comment>
    <dependence roles="Oneway" />
  </role>

  <!-- ====================================================================== -->
  <role name="Senderimpl" min="1" max="1">
    <comment>
      <li>maintains a reference to a Oneway service type.</li>
      <li>The Sender component calls the Receiver component without waiting for a response.</li>
    </comment>
    <dependence roles="Oneway" />
  </role>

</pattern>

=== stevencapelli/SCA-PatternBOX/editor-plugin/pattern.mf/requestresponse.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE pattern SYSTEM "manifest.dtd">
<pattern id="requestresponse"
         name="Requestresponse"
         topCategorie="SCA"
         subCategorie="Micro Pattern">

  <comment>
    Micropattern- Define a type of interaction where the calling component sends a message to the called component.THe calling component expects an immediate response for each message that's sent.
  </comment>

  <!-- ====================================================================== -->
  <role name="Requestresponse" min="1" max="1">
    <comment>
      <li>defines an interface offering services to the requesting component.</li>
    </comment>
  </role>

  <!-- ====================================================================== -->
  <role name="ServerImpl" min="1" max="1">
    <comment>
      <li>implements the request services by providing the RequestResponse interface.</li>
    </comment>
    <dependence roles="Requestresponse" />
  </role>

  <!-- ====================================================================== -->
  <role name="ClientRequestresponseImpl" min="1" max="1">
    <comment>
      <li>maintains a reference to a RequestResponse service type.</li>
      <li>calls a service of the Server component and waits for the resutl</li>
    </comment>
    <dependence roles="Requestresponse" />
  </role>

</pattern>

=== stevencapelli/SCA-PatternBOX/editor-plugin/pattern.mf/observer.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE pattern SYSTEM "manifest.dtd">
<pattern id="observer"
         name="Observer"
         topCategorie="GoF"
         subCategorie="Behavioral Pattern">

  <comment>
    Define a one-to-many dependency between objects so that when one object
    changes state, all its dependents are notified and updated automatically.
  </comment>

  <!-- ====================================================================== -->
  <role name="Subject" min="1" max="1">
    <comment>
      <li>knows its observers. Any number of Observer objects may observe a subject.</li>
      <li>provides an interface for attaching and detaching Observer objects.</li>
    </comment>
    <dependence roles="Observer" />
  </role>

  <!-- ====================================================================== -->
  <role name="Observer" min="1" max="1">
    <comment>
      <li>defines an updating interface for objects that should be notified of changes in a subject.</li>
    </comment>
  </role>

  <!-- ====================================================================== -->
  <role name="ConcreteSubject" min="1" max="1">
    <comment>
      <li>stores state of interest to ConcreteObserver objects.</li>
      <li>sends a notification to its observers when its state changes.</li>
    </comment>
    <dependence roles="Subject State" />
  </role>

  <!-- ====================================================================== -->
  <role name="ConcreteObserver" min="1" max="n">
    <comment>
      <li>maintains a reference to a ConcreteSubject object.</li>
      <li>stores state that should stay consistent with the subject's. </li>
      <li>implements the Observer updating interface to keep its state consistent with the subject's.</li>
    </comment>
    <dependence roles="Observer State" />
  </role>

  <!-- ====================================================================== -->
  <role name="State" min="1" max="1">
    <comment>
      <li>represents states of interest to ConcreteObserver and ConcreteObserver objects.</li>
      <li>is just a marker interface to make to code more type safe.</li>
    </comment>
  </role>

</pattern>

=== stevencapelli/SCA-PatternBOX/editor-plugin/pattern.mf/strategy.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE pattern SYSTEM "manifest.dtd">
<pattern id="strategy"
         name="Strategy"
         topCategorie="GoF"
         subCategorie="Behavioral Pattern">

  <comment>
    Define a family of algorithms, encapsulate each one, and make them interchangeable.
    Strategy lets the algorithm vary independently from clients that use it.
  </comment>

  <!-- ====================================================================== -->
  <role name="Strategy" min="1" max="1">
    <comment>
      <li>declares an interface common to all supported algorithms. Context uses this interface to call the algorithm defined by a ConcreteStrategy.</li>
    </comment>
  </role>

  <!-- ====================================================================== -->
  <role name="ConcreteStrategy" min="1" max="n">
    <comment>
      <li>implements the algorithm using the Strategy interface.</li>
    </comment>
    <dependence roles="Strategy" />
  </role>

  <!-- ====================================================================== -->
  <role name="Context" min="1" max="1">
    <comment>
      <li>is configured with a ConcreteStrategy object.</li>
      <li>maintains a reference to a Strategy object.</li>
      <li>may define an interface that lets Strategy access its data.</li>
    </comment>
    <dependence roles="Strategy" />
  </role>

</pattern>

=== stevencapelli/SCA-PatternBOX/editor-plugin/pattern.mf/routingfiltering.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE pattern SYSTEM "manifest.dtd">
<pattern id="routingfiltering"
         name="Routingfiltering"
         topCategorie="SCA"
         subCategorie="SOA Pattern">

  <comment>
   SOA pattern. Messages must be dispatched to various components based on their payload, attributes.
  </comment>

  <!-- ====================================================================== -->
  <role name="Data" min="1" max="1">
    <comment>
      <li>defines the type of messages that must be dispatched.</li>
    </comment>
  </role>

  <!-- ====================================================================== -->
  <role name="Category" min="1" max="1">
    <comment>
      <li>defines the type of messages that must be dispatched.</li>
    </comment>
  </role>

  <!-- ====================================================================== -->
 <role name="FilterSend" min="1" max="1">
    <comment>
      
      <li>Defines the methods implemented by the Filter component.</li>
    </comment>
  </role>

  <!-- ====================================================================== -->
  <role name="ReceiverSend" min="1" max="1">
    <comment>
      <li>Defines the methods implemented by the Receiver component.</li>
    </comment>
  </role>

  <!-- ====================================================================== -->
  <role name="RouterSend" min="1" max="1">
    <comment>
      <li>Defines the methods implemented by the Router component.</li>
    </comment>
  </role>
<!-- ====================================================================== -->
  <role name="Sender" min="1" max="1">
    <comment>
      <li>Sender component uses this interface to send the messages to the Receiver components.</li>
    </comment>

  </role>
<!-- ====================================================================== -->
  <role name="SenderImpl" min="1" max="1">
    <comment>
      <li>Sets the messages and sends the messages to the Filter component.</li>
    </comment>
 <dependence roles="Sender RouterSend ReceiverSend FilterSend Data"/>
  </role>
<!-- ====================================================================== -->
  <role name="FilterImpl" min="1" max="1">
    <comment>
      <li>the Filter component filters the messages.</li>
    </comment>
 <dependence roles="Sender RouterSend ReceiverSend FilterSend Data"/>
  </role>
<!-- ====================================================================== -->  <role name="RouterImpl" min="1" max="1">
    <comment>
      <li>The Router component routes the messages to the Receiver components.</li>
    </comment>

  </role>
<!-- ====================================================================== -->
 <role name="ReceiverImpl" min="1" max="n">
    <comment>
      <li>The Receiver component receives the messages from the Sender components.</li>
    </comment>

  </role>
<!-- ====================================================================== -->
</pattern>

=== stevencapelli/SCA-PatternBOX/editor-plugin/pattern.mf/command.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE pattern SYSTEM "manifest.dtd">
<pattern id="command"
         name="Command"
         topCategorie="GoF"
         subCategorie="Behavioral Pattern">

  <comment>
    Encapsulate a request as an object, thereby letting you parameterize clients with
    different requests, queue or log requests, and support undoable operations.
  </comment>

  <!-- ====================================================================== -->
  <role name="Command" min="1" max="1">
    <comment>
      <li>declares an interface for executing an operation.</li>
    </comment>
  </role>

  <!-- ====================================================================== -->
  <role name="ConcreteCommand" min="1" max="n">
    <comment>
      <li>defines a binding between a Receiver object and an action.</li>
      <li>implements Execute by invoking the corresponding operation(s) on Receiver.</li>
    </comment>
    <dependence roles="Command Receiver" />
  </role>

  <!-- ====================================================================== -->
  <role name="Client" min="1" max="n">
    <comment>
      <li>creates a ConcreteCommand object and sets its receiver.</li>
    </comment>
    <dependence roles="ConcreteCommand Receiver" />
  </role>

  <!-- ====================================================================== -->
  <role name="Invoker" min="1" max="1">
    <comment>
      <li>asks the command to carry out the request.</li>
    </comment>
    <dependence roles="Command" />
  </role>

  <!-- ====================================================================== -->
  <role name="Receiver" min="1" max="1">
    <comment>
      <li>knows how to perform the operations associated with carrying out a request. Any class may serve as a Receiver.</li>
    </comment>
  </role>

</pattern>

=== stevencapelli/SCA-PatternBOX/editor-plugin/pattern.mf/callback.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE pattern SYSTEM "manifest.dtd">
<pattern id="callback"
         name="Callback"
         topCategorie="SCA"
         subCategorie="Micro Pattern">

  <comment>
   Micropattern. A forward message from calling to called component instigates a call from the called component back to the calling component at some point in the future. This is referred to as the callback direction. When no callback is configured, messages travel in the forward direction only.
  </comment>

  <!-- ====================================================================== -->
  <role name="ForwardInterface" min="1" max="1">
    <comment>
      <li>define the forward interface</li>
    </comment>
  </role>

  <!-- ====================================================================== -->
  <role name="ServerImpl" min="1" max="1">
    <comment>
      
      <li>implements the forward interface and uses the callback interface to notify the result back to the client.</li>
<li>maintains a reference (the callback proxy) to point back to the client component.</li>
    </comment>
    <dependence roles="ForwardInterface InterfaceCallback" />
  </role>

  <!-- ====================================================================== -->
  <role name="InterfaceCallback" min="1" max="1">
    <comment>
      <li>defines the Callback interface.</li>
    </comment>

  </role>

  <!-- ====================================================================== -->
  <role name="ClientCallbackImpl" min="1" max="1">
    <comment>
      <li>maintains a reference to a Forward service type.</li>
  <li>implements the callback interface.</li>
    </comment>
    <dependence roles="InterfaceCallback ForwardInterface" />
  </role>

</pattern>
