=== stevencapelli/SCA-PatternBOX/editor-plugin/pattern.mf/manifest.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- 
  
  Copyright (C)2003-2012 by Dirk Ehms, www.patternbox.com. 
  All rights reserved. 
  
  This DTD module is identified by the SYSTEM identifier:
  SYSTEM "manifest.dtd"

  Version: 1.1
  Date:    2003-09-23

-->

<!ELEMENT pattern (comment,role+)>
<!ATTLIST pattern
  id            NMTOKEN   #REQUIRED
  name          CDATA     #REQUIRED
  topCategorie  CDATA     #REQUIRED
  subCategorie  CDATA     #IMPLIED
  authorName    CDATA     "Dirk Ehms"
  authorWebsite CDATA     "www.patternbox.com"
>

<!-- design pattern participant -->
<!ELEMENT role (comment,dependence?)>
<!ATTLIST role
  name          ID        #REQUIRED
  min           NMTOKEN   #REQUIRED
  max           NMTOKEN   #REQUIRED
>

<!-- role dependence -->
<!ELEMENT dependence EMPTY>
<!ATTLIST dependence
  roles         IDREFS    #REQUIRED
>

<!-- pattern|role comment -->
<!ELEMENT comment (#PCDATA|li)*>

<!-- comment list item -->
<!ELEMENT li (#PCDATA)>

=== stevencapelli/SCA-PatternBOX/editor-plugin/pattern.mf/remote.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE pattern SYSTEM "manifest.dtd">
<pattern id="remote"
         name="Remote"
         topCategorie="SCA"
         subCategorie="Micro Pattern">

  <comment>
   Micropattern. This interaction pattern allows SCA components to communicate with other remote SCA components or non-SCA software using pass-by-value-semantics.
  </comment>

  <!-- ====================================================================== -->
  <role name="RemoteInteraction" min="1" max="1">
    <comment>
      <li>declares an interface offering services provided by a remote component.</li>
    </comment>
  </role>

  <!-- ====================================================================== -->
  <role name="ServerRemoteInteraction" min="1" max="1">
    <comment>
      <li>implements the services by providing the remote interface.</li>
    </comment>
    <dependence roles="RemoteInteraction" />
  </role>

  <!-- ====================================================================== -->
  <role name="ClientRemoteInteraction" min="1" max="1">
    <comment>
      <li>maintains a reference to a Remote service type.</li>
      <li>calls a service of a remote server component.</li>
    </comment>
    <dependence roles="RemoteInteraction" />
  </role>

</pattern>

=== stevencapelli/SCA-PatternBOX/editor-plugin/pattern.mf/facade.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE pattern SYSTEM "manifest.dtd">
<pattern id="facade"
         name="Facade"
         topCategorie="GoF"
         subCategorie="Structural Pattern">

  <comment>
    Provide a unified interface to a set of interfaces in a subsystem. Facade defines a
    higher-level interface that makes the subsystem easier to use.
  </comment>

  <!-- ====================================================================== -->
  <role name="Facade" min="1" max="1">
    <comment>
      <li>knows which subsystem classes are responsible for a request.</li>
      <li>delegates client requests to appropriate subsystem objects.</li>
    </comment>
    <dependence roles="Subsystem" />
  </role>

  <!-- ====================================================================== -->
  <role name="Subsystem" min="1" max="1">
    <comment>
      <li>implement subsystem functionality.</li>
      <li>handle work assigned by the Facade object.</li>
      <li>have no knowledge of the facade; that is, they keep no references to it.</li>
    </comment>
  </role>

</pattern>

=== stevencapelli/SCA-PatternBOX/editor-plugin/pattern.mf/templatemethod.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE pattern SYSTEM "manifest.dtd">
<pattern id="templatemethod"
         name="Template Method"
         topCategorie="GoF"
         subCategorie="Behavioral Pattern">

  <comment>
    Define the skeleton of an algorithm in an operation, deferring some steps to subclasses.
    Template Method lets subclasses redefine certain steps of an algorithm without changing
    the algorithm's structure.
  </comment>

  <!-- ====================================================================== -->
  <role name="AbstractClass" min="1" max="1">
    <comment>
      <li>defines abstract primitive operations that concrete subclasses define to implement steps of an algorithm.</li>
      <li>implements a template method defining the skeleton of an algorithm. The template method calls primitive operations as well as operations defined in AbstractClass or those of other objects.</li>
    </comment>
  </role>

  <!-- ====================================================================== -->
  <role name="ConcreteClass" min="1" max="n">
    <comment>
      <li>implements the primitive operations to carry out subclass-specific steps of the algorithm.</li>
    </comment>
    <dependence roles="AbstractClass" />
  </role>

</pattern>

=== stevencapelli/SCA-PatternBOX/editor-plugin/pattern.mf/replicator.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE pattern SYSTEM "manifest.dtd">
<pattern id="replicator"
         name="Replicator"
         topCategorie="SCA"
         subCategorie="SOA Pattern">

  <comment>
   SOA pattern. Messages or payloads must be replicated across multiple endpoints with identical configurations.
  </comment>

  <!-- ====================================================================== -->
  <role name="Message" min="1" max="1">
    <comment>
      <li>declares an interface common to all supported algorithms. Message component uses this interface to send a message to the client </li>
    </comment>
  </role>

  <!-- ====================================================================== -->
  <role name="MessageImpl" min="1" max="1">
    <comment>
      
      <li>implements the algorithm using the Message interface.</li>
    </comment>
     <dependence roles="Message Replicator Client" />
  </role>

  <!-- ====================================================================== -->
  <role name="Replicator" min="1" max="1">
    <comment>
      <li>the interface through which the service will perform the replicator</li>
    </comment>

  </role>

  <!-- ====================================================================== -->
  <role name="ReplicatorImpl" min="1" max="1">
    <comment>
      <li>The component Replicator replicate the message to the clients</li>
    </comment>
 <dependence roles="Message Replicator Client" />
  </role>
<!-- ====================================================================== -->
  <role name="Client" min="1" max="1">
    <comment>
      <li>Client components use this interface</li>
    </comment>

  </role>
<!-- ====================================================================== -->
  <role name="ClientImpl" min="1" max="n">
    <comment>
      <li>Implements the algorithm using the Client interface</li>
    </comment>
 <dependence roles="Message Replicator Client"/>
  </role>

</pattern>

=== stevencapelli/SCA-PatternBOX/editor-plugin/pattern.mf/prototype.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE pattern SYSTEM "manifest.dtd">
<pattern id="prototype"
         name="Prototype"
         topCategorie="GoF"
         subCategorie="Creational Pattern">

  <comment>
    Specify the kinds of objects to create using a prototypical instance, and create new
    objects by coping this prototype.
  </comment>

  <!-- ====================================================================== -->
  <role name="Prototype" min="1" max="1">
    <comment>
      <li>declares an interface for cloning itself.</li>
    </comment>
  </role>

  <!-- ====================================================================== -->
  <role name="ConcretePrototype" min="1" max="n">
    <comment>
      <li>declares an operation for cloning itself.</li>
    </comment>
    <dependence roles="Prototype" />
  </role>

  <!-- ====================================================================== -->
  <role name="Client" min="1" max="n">
    <comment>
      <li>creates a new object by asking a prototype to clone itself.</li>
    </comment>
    <dependence roles="Prototype" />
  </role>

</pattern>

=== stevencapelli/SCA-PatternBOX/editor-plugin/pattern.mf/PingEchoHeartBeat.xml
<!DOCTYPE pattern SYSTEM "manifest.dtd">
<pattern id="pingechoheartbeat" name="Heartbeat" topCategorie="SCA">

<comment> One sender component sends a heart beat message to a receiver periodically.
The aliveness of the sender is checked by the receiver regularly every specified time interval.
If the heartbeat message is not received within a certain maximum waiting, the sender is
considered to be unavailable.
</comment>
<!-- ======================================================================================== -->
<role name="PingEchoHeartbeatService" min="1" max="1" type="Interface" operation="imAlive">
<comment>
<li>Defines an interface for the heart beat sending service.</li>
</comment>
</role>

<!-- ======================================================================================= -->
<role name="PingEchoHeartbeatSender" min="1" max="1" type="Component" property= "timeInterval beatTimeInterval maxWaitingTime">
<comment> 
<li>Maintains a reference to one or more Receiver services.</li>
<li>Sends an heartbeat message to a Receiver component. </li> 
</comment>
<dependence role="PingEchoHeartBeatService" type="required"/>
</role>

<!-- ========================================================================================== -->
<role name="PingEchoHeartbeatReceiver" min="1" max="1" type="Component" property= "timeInterval maxWaitingTime">
<comment> 
<li>Maintains a reference to a Sender service.</li>
<li>Receives an heart beat from a sender periodically.</li>
</comment>
<dependence role="PingEchoHeartbeatService" type="provided"/>
</role>
</pattern>

=== stevencapelli/SCA-PatternBOX/editor-plugin/pattern.mf/HeartBeat.xml
<!DOCTYPE pattern SYSTEM "manifest.dtd">
<pattern id="heartbeat" name="Heartbeat" topCategorie="SCA">
<comment> One sender component sends a heart beat message to a receiver periodically.
The aliveness of the sender is checked by the receiver regularly every specified time interval.
If the heartbeat message is not received within a certain maximum waiting, the sender is
considered to be unavailable.
</comment>
<role name="HeartbeatService" min="1" max="1" type="Interface" operation="imAlive">
<comment>
<li>Defines an interface for the heart beat sending service.</li>
</comment>
<role name="HeartbeatSender" min="1" max="1" type="Component" property= "timeInterval">
<comment> 
<li>Maintains a reference to one or more Receiver services.</li>
<li>Sends an heartbeat message to a Receiver component. </li> 
</comment>
<dependence role="HeartBeatService" type="required"/>
</role>
<role name="HeartbeatReceiver" min="1" max="1" type="Component" property= "timeInterval maxWaitingTime">
<comment> 
<li>Maintains a reference to a Sender service.</li>
<li>Receives an heart beat from a sender periodically.</li>
</comment>
<dependence role="HeartbeatService" type="provided"/>
</role>
</role>
</pattern>

=== stevencapelli/SCA-PatternBOX/editor-plugin/pattern.mf/builder.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE pattern SYSTEM "manifest.dtd">
<pattern id="builder"
         name="Builder"
         topCategorie="GoF"
         subCategorie="Creational Pattern">

  <comment>
    Separate the construction of a complex object from its representation so that
    the same construction process can create different representations.
  </comment>

  <!-- ====================================================================== -->
  <role name="Builder" min="1" max="1">
    <comment>
      <li>specifies an abstract interface for creating parts of a Product object.</li>
    </comment>
  </role>

  <!-- ====================================================================== -->
  <role name="ConcreteBuilder" min="1" max="n">
    <comment>
      <li>constructs and assembles parts of the product by implementing the Builder interface.</li>
      <li>defines and keeps track of the representation it creates.</li>
      <li>provides an interface for retrieving the product.</li>
    </comment>
    <dependence roles="Builder Product" />
  </role>

  <!-- ====================================================================== -->
  <role name="Director" min="1" max="1">
    <comment>
      <li>constructs an object using the Builder interface.</li>
    </comment>
    <dependence roles="Builder" />
  </role>

  <!-- ====================================================================== -->
  <role name="Product" min="1" max="1">
    <comment>
      <li>represents the complex object under construction. ConcreteBuilder builds the product's internal representation and defines the process by which it's assembled.</li>
      <li>includes classes that define the constituent parts, including interfaces for assembling the parts into the final result.</li>
    </comment>
  </role>

  <!-- ====================================================================== -->
  <role name="Client" min="1" max="n">
    <comment>
      <li>requests the services from Director to construct a complex object.</li>
    </comment>
    <dependence roles="ConcreteBuilder Director" />
  </role>

</pattern>
