=== stevencapelli/SCA-PatternBOX/editor-plugin/pattern.mf/manifest.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- 
  
  Copyright (C)2003-2012 by Dirk Ehms, www.patternbox.com. 
  All rights reserved. 
  
  This DTD module is identified by the SYSTEM identifier:
  SYSTEM "manifest.dtd"

  Version: 1.1
  Date:    2003-09-23

-->

<!ELEMENT pattern (comment,role+)>
<!ATTLIST pattern
  id            NMTOKEN   #REQUIRED
  name          CDATA     #REQUIRED
  topCategorie  CDATA     #REQUIRED
  subCategorie  CDATA     #IMPLIED
  authorName    CDATA     "Dirk Ehms"
  authorWebsite CDATA     "www.patternbox.com"
>

<!-- design pattern participant -->
<!ELEMENT role (comment,dependence?)>
<!ATTLIST role
  name          ID        #REQUIRED
  min           NMTOKEN   #REQUIRED
  max           NMTOKEN   #REQUIRED
>

<!-- role dependence -->
<!ELEMENT dependence EMPTY>
<!ATTLIST dependence
  roles         IDREFS    #REQUIRED
>

<!-- pattern|role comment -->
<!ELEMENT comment (#PCDATA|li)*>

<!-- comment list item -->
<!ELEMENT li (#PCDATA)>

=== stevencapelli/SCA-PatternBOX/editor-plugin/pattern.mf/Layer.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE pattern SYSTEM "manifest.dtd">
<pattern id="PatternLayer"
         name="PatternLayer"
         topCategorie="SCA"
         subCategorie="SOA Pattern">

  <comment>
   SOApattern. three-layer architectural pattern.
  </comment>

  <!-- ====================================================================== -->
  <role name="ApplicationService" min="1" max="n">
    <comment>
      <li>defines an interface offering services to send command</li>
    </comment>
  </role>

  <!-- ====================================================================== -->
  <role name="PersistenceService" min="1" max="1">
    <comment>
      <li>defines an interface offering services to update data</li>
    </comment>
  </role>
<!-- ====================================================================== -->
  <role name="QueryService" min="1" max="1">
    <comment>
      <li>defines an interface offering services to get data</li>
    </comment>

  </role>
<!-- ====================================================================== -->
  <role name="Application" min="1" max="1">
    <comment>
      <li>Application component takes arriving command</li>
    </comment>

  </role>
<!-- ====================================================================== -->
  <role name="GUI" min="1" max="1">
    <comment>
      <li>GUI componennt send command to application component</li>
    </comment>

  </role>

<!-- ====================================================================== -->
  <role name="Data" min="1" max="1">
    <comment>
      <li>Data component manages data</li>
    </comment>

  </role>

</pattern>

=== stevencapelli/SCA-PatternBOX/editor-plugin/pattern.mf/pingecho.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE pattern SYSTEM "manifest.dtd">
<pattern id="pingecho"
         name="PingEcho"
         topCategorie="SCA"
         subCategorie="SOA Pattern">

  <comment>
   SOA pattern. The PingEcho pattern is used to determine if a Server is reachable by sending it a message (Ping) to which it will respond with another message (Echo).
  </comment>

  <!-- ====================================================================== -->
  <role name="Sender" min="1" max="1">
    <comment>
      <li> Sender uses this interface to run the pattern</li>
    </comment>
  </role>

  <!-- ====================================================================== -->
  <role name="Receiver" min="1" max="1">
    <comment>
      
      <li> Receiver uses this interface to offer service.</li>
    </comment>
 
 </role>

  <!-- ====================================================================== -->
  <role name="SenderImpl" min="1" max="1">
    <comment>
      <li>The Sender Component sends a message (Ping) to the Receiver component</li>
    </comment>
 <dependence roles="Sender Receiver" />
  </role>

  <!-- ====================================================================== -->
  <role name="ReceiverImpl" min="1" max="1">
    <comment>
      <li>The Receiver Component receives the Ping and responses with the Echo</li>
    </comment>
    <dependence roles="Sender Receiver"/>
  </role>

</pattern>

=== stevencapelli/SCA-PatternBOX/editor-plugin/pattern.mf/iterator.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE pattern SYSTEM "manifest.dtd">
<pattern id="iterator"
         name="Iterator"
         topCategorie="GoF"
         subCategorie="Behavioral Pattern">

  <comment>
    Provide a way to access the elements of an aggregate object sequentially
    without exposing its underlying representation.
  </comment>

  <!-- ====================================================================== -->
  <role name="Iterator" min="1" max="1">
    <comment>
      <li>defines an interface for accessing and traversing elements.</li>
    </comment>
  </role>

  <!-- ====================================================================== -->
  <role name="ConcreteIterator" min="1" max="1">
    <comment>
      <li>implements the Iterator interface.</li>
      <li>keeps track of the current position in the traversal of the aggregate.</li>
    </comment>
    <dependence roles="Iterator ConcreteAggregate" />
  </role>

  <!-- ====================================================================== -->
  <role name="Aggregate" min="1" max="1">
    <comment>
      <li>defines an interface for creating an Iterator object.</li>
    </comment>
  </role>

  <!-- ====================================================================== -->
  <role name="ConcreteAggregate" min="1" max="1">
    <comment>
      <li>implements the Iterator creation interface to return an instance of the proper ConcreteIterator.</li>
    </comment>
    <dependence roles="Aggregate" />
  </role>

</pattern>

=== stevencapelli/SCA-PatternBOX/editor-plugin/pattern.mf/state.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE pattern SYSTEM "manifest.dtd">
<pattern id="state"
         name="State"
         topCategorie="GoF"
         subCategorie="Behavioral Pattern">

  <comment>
    Allow an object to alter its behavior when its internal state changes. The object
    will appear to change its class.
  </comment>

  <!-- ====================================================================== -->
  <role name="Context" min="1" max="1">
    <comment>
      <li>defines the interface of interest to clients.</li>
      <li>maintains an instance of a ConcreteState subclass that defines the current state.</li>
    </comment>
    <dependence roles="State" />
  </role>

  <!-- ====================================================================== -->
  <role name="State" min="1" max="1">
    <comment>
      <li>defines an interface for encapsulating the behavior associated with a particular state of the Context.</li>
    </comment>
  </role>

  <!-- ====================================================================== -->
  <role name="ConcreteState" min="1" max="n">
    <comment>
      <li>each subclass implements a behavior associated with a state of the Context.</li>
    </comment>
    <dependence roles="State Context" />
  </role>

</pattern>

=== stevencapelli/SCA-PatternBOX/editor-plugin/pattern.mf/publishsubscribe.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE pattern SYSTEM "manifest.dtd">
<pattern id="publishsubscribe"
         name="Publishsubscribe"
         topCategorie="SCA"
         subCategorie="SOA Pattern">

  <comment>
   SOA pattern. A mechanism for routing messages to consumers in response to specific events in the SOA or triggered by specific applications running in the SOA.
  </comment>

  <!-- ====================================================================== -->
  <role name="Data" min="1" max="1">
    <comment>
      <li>defines the type of messages that must be dispatched.</li>
    </comment>
<dependence roles="Category"/>  
</role>

  <!-- ====================================================================== -->
  <role name="Category" min="1" max="1">
    <comment>
      <li>defines the type of messages that must be dispatched.</li>
    </comment>

  </role>

  <!-- ====================================================================== -->
 <role name="Publisher" min="1" max="1">
    <comment>
      
      <li>Defines the methods implemented by the Publisher component.</li>
    </comment>
  </role>

  <!-- ====================================================================== -->
  <role name="DispatchPub" min="1" max="1">
    <comment>
      <li>Defines the methods implemented by the Dispatch component and offered to the Publisher component.</li>
    </comment>
  </role>

  <!-- ====================================================================== -->
  <role name="DispatchSub" min="1" max="1">
    <comment>
      <li>Defines the methods implemented by the Dispatch component and offered to the Subscriber component.</li>
    </comment>
  </role>
<!-- ====================================================================== -->
  <role name="SubscriberCommunicate" min="1" max="1">
    <comment>
      <li>Defines the methods implemented by the Subscriber component.</li>
    </comment>

  </role>
<!-- ====================================================================== -->
  <role name="RowList" min="1" max="1">
    <comment>
      <li>Defines the structure of the Dispatch.</li>
    </comment>
 <dependence roles="Data Category DispatchSub DispatchPub SubscriberCommunicate Publisher"/>
  </role>
<!-- ====================================================================== -->
  <role name="PublisherImpl" min="1" max="1">
    <comment>
      <li>the Publischer component send the messages.</li>
    </comment>
<dependence roles="Data Category DispatchSub DispatchPub SubscriberCommunicate Publisher"/>
  </role>
<!-- ====================================================================== -->  
<role name="DispatcherImpl" min="1" max="1">
    <comment>
      <li>The Dispatcher component dispatches the messages to the Subscriber components.</li>
    </comment>
<dependence roles="Data Category DispatchSub DispatchPub SubscriberCommunicate Publisher"/>
  </role>
<!-- ====================================================================== -->
 <role name="SubscriberImpl" min="1" max="n">
    <comment>
      <li>The Subscriber component receives the messages from the Publisher component.</li>
    </comment>
<dependence roles="Data Category DispatchSub DispatchPub SubscriberCommunicate Publisher"/>
  </role>

</pattern>

=== stevencapelli/SCA-PatternBOX/editor-plugin/pattern.mf/singleton.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE pattern SYSTEM "manifest.dtd">
<pattern id="singleton"
         name="Singleton"
         topCategorie="GoF"
         subCategorie="Creational Pattern">

  <comment>
    Ensure a class only has one instance, and provide a global point of access to it.
  </comment>

  <!-- ====================================================================== -->
  <role name="Singleton" min="1" max="1">
    <comment>
      <li>defines an Instance operation that lets clients access its unique instance. Instance is a class operation</li>
      <li>may be responsible for creating its own unique instance.</li>
    </comment>
  </role>

  <!-- ====================================================================== -->
  <role name="Client" min="1" max="n">
    <comment>
      <li>requests the Singleton to get its unique instance.</li>
    </comment>
    <dependence roles="Singleton" />
  </role>

</pattern>

=== stevencapelli/SCA-PatternBOX/editor-plugin/pattern.mf/fifo.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE pattern SYSTEM "manifest.dtd">
<pattern id="fifo"
         name="Fifo"
         topCategorie="SCA"
         subCategorie="SOA Pattern">

  <comment>
   SOApattern. A mechanism for manipulate datas with a queue processing technique.
  </comment>

  <!-- ====================================================================== -->
  <role name="Sender" min="1" max="1">
    <comment>
      <li>defines an interface offering services to the Sender component</li>
    </comment>
  </role>

  <!-- ====================================================================== -->
  <role name="Receiver" min="1" max="1">
    <comment>
      
      <li>defines an interface offering services to the Receiver component</li>
    </comment>
  </role>

  <!-- ====================================================================== -->
  <role name="FifoEnqueue" min="1" max="1">
    <comment>
      <li>the interface through which the sender will perform the function enqueue into the fifo.</li>
    </comment>

  </role>

  <!-- ====================================================================== -->
  <role name="FifoDequeue" min="1" max="1">
    <comment>
      <li>the interface through which the receiver will perform the function dequeue from the fifo.</li>
    </comment>
  </role>
<!-- ====================================================================== -->
  <role name="SenderImpl" min="1" max="1">
    <comment>
      <li>Sender inserts elements into the fifo.</li>
    </comment>

  </role>
<!-- ====================================================================== -->
  <role name="FifoImpl" min="1" max="1">
    <comment>
      <li>Fifo component manages the method enqueue adn dequeue </li>
    </comment>

  </role>
<!-- ====================================================================== -->
  <role name="ReceiverImpl" min="1" max="1">
    <comment>
      <li>Receiver pulls elements from the fifo.</li>
    </comment>

  </role>

</pattern>

=== stevencapelli/SCA-PatternBOX/editor-plugin/pattern.mf/composite.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE pattern SYSTEM "manifest.dtd">
<pattern id="composite"
         name="Composite"
         topCategorie="GoF"
         subCategorie="Structural Pattern">

  <comment>
    Compose objects into tree structures to represent part-whole hierarchies. Composite
    lets clients treat individual objects and compositions of objects uniformly.
  </comment>

  <!-- ====================================================================== -->
  <role name="Component" min="1" max="1">
    <comment>
      <li>declares the interface for objects in the composition.</li>
      <li>implements default behavior for the interface common to all classes, as appropriate.</li>
      <li>declares an interface for accessing and managing its child components.</li>
      <li>(optional) defines an interface for accessing a component's parent in the recursive structure, and implements it if that's appropriate.</li>
    </comment>
  </role>

  <!-- ====================================================================== -->
  <role name="Leaf" min="1" max="n">
    <comment>
      <li>represents leaf objects in the composition. A leaf has no children.</li>
      <li>defines behavior for primitive objects in the composition.</li>
    </comment>
    <dependence roles="Component" />
  </role>

  <!-- ====================================================================== -->
  <role name="Composite" min="1" max="1">
    <comment>
      <li>defines behavior for components having children.</li>
      <li>stores child components.</li>
      <li>implements child-related operations in the Component interface.</li>
    </comment>
    <dependence roles="Component" />
  </role>

  <!-- ====================================================================== -->
  <role name="Client" min="1" max="1">
    <comment>
      <li>manipulates objects in the composition through the Component interface.</li>
    </comment>
    <dependence roles="Component Leaf Composite" />
  </role>

</pattern>
